---
title: "r01_DEG_mRNA_p16_siVirma"
author: "Tang Li"
date: '2023-2-11'
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(DESeq2)
library(GEOquery)
library(GenomicFeatures)
library(BiocParallel)
library(GenomicAlignments)
library(rtracklayer)
library(NMF)
library(parallel)
library(Rsubread)
library(RUVSeq)
library(stringr)
library(data.table)
library(ggplot2)
library(ggprism)
library(RColorBrewer)
library(ttFunctions)
library(ggthemes)
library(ggsci)
library(ggpubr)
library(ComplexHeatmap)
library(sva)
library(venn)
options(stringsAsFactors = FALSE)
library(ggrepel)
library(clusterProfiler)
library(org.Mm.eg.db)
library(biomaRt)
library(enrichplot)
library(patchwork)
library(VennDiagram)

# ~/Data/01_TC1/01_mRNA_expression/05_p16_siVirma/05_p16_siVirma.Rproj

require("knitr")
opts_knit$set(root.dir = file.path("~/Data/01_TC1/01_mRNA_expression/05_p16_siVirma/"))

```

```{r filt genes with duplicated gene name}
fc_result_count <- read.table("../01_p0p5p10rp2/01_featureCounts/express_matrix_count.txt")
fc_result_annotation <- read.table("../01_p0p5p10rp2/01_featureCounts/express_matrix_annotation.txt")

table(duplicated(fc_result_annotation$gene_name))

fc_result_count <- fc_result_count[!duplicated(fc_result_annotation$gene_name),]
fc_result_annotation <- fc_result_annotation[rownames(fc_result_count),]

rownames(fc_result_count) <- fc_result_annotation$gene_name
rownames(fc_result_annotation) <- fc_result_annotation$gene_name


```

```{r marker genes}
marker_all <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//all")$V1
marker_toti <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//toti")$V1
marker_pluri <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//pluri")$V1
marker_TE_TSC <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//TE_TSC")$V1
marker_PrE_XEN <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//PrE_XEN")$V1
marker_APA <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//APA")$V1
marker_APAperturb <- read.table("~/Data/01_TC1/00_gene_set/all/APA_perturb")$V1

table(marker_all %in% rownames(express_matrix))
marker_all[!marker_all %in% rownames(express_matrix)]
marker_all <- marker_all[marker_all %in% rownames(express_matrix)]
```
### DEG for p16_siVirma

```{r betweenLaneNormalization & expression filter10}
colnames(fc_result_count)
sample_name <- c("siNC_rep1","siNC_rep2","siM3_1_rep1","siM3_2_rep1","siVirma_rep1","siVirma_rep2")
express_matrix <- fc_result_count[,11:16]
colnames(express_matrix) <- sample_name
meta_data <- data.frame(rep = c("rep1","rep2","rep1","rep1","rep1","rep2"),
                        stage = c("siNC","siNC","siM3_1","siM3_2","siVirma","siVirma"),
                        row.names = sample_name,
                        sample_name = sample_name,
                        stringsAsFactors = TRUE)
meta_data

x <- meta_data$stage
set <- newSeqExpressionSet(as.matrix(express_matrix),
                           phenoData = data.frame(x, row.names=colnames(express_matrix)))
set

colors <- brewer.pal(18, "Paired")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

set <- betweenLaneNormalization(set, which="upper")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

express_matrix <- set@assayData$normalizedCounts

dir.create("02_express_matrix")
tt_wt(express_matrix,"02_express_matrix/express_matrix.txt",row.names=T,col.names = T)
# 对表达量进行筛选
filter <- rowSums(express_matrix>10)>=2
table(filter)
express_matrix_filter10 <- express_matrix[filter,]

colnames(express_matrix_filter10)
tt_wt(express_matrix_filter10,"02_express_matrix/express_matrix_filter10.txt",row.names=T,col.names = T)
```

```{r get tpm_matrix}
#convert to TPM

tpm_matrix <- do.call(cbind,base::lapply(colnames(express_matrix),FUN = function(x){
  counts <- express_matrix[,x]
  effLen <- fc_result_annotation[rownames(express_matrix),"Length"]
  rate <- log(counts) - log(effLen)
  denom <- log(sum(exp(rate)))
  return(exp(rate-denom+log(1e6)))
}))

rownames(tpm_matrix) <- rownames(express_matrix)
colnames(tpm_matrix) <- colnames(express_matrix)
table(colSums(tpm_matrix))

write.table(tpm_matrix,file="02_express_matrix/tpm_matrix.txt",quote = F,sep = "\t")
```


```{r marker barplot}
tpm_matrix[rownames(tpm_matrix) %in% marker_APA,]

tt_barplot <- function(gene_name){
  temp <- data.frame(group=factor(c("siNC","siNC","siM3","siVirma","siVirma"),levels = c("siNC","siM3","siVirma")),
                   tpm=tpm_matrix[gene_name,c(1,2,4,5,6)])
  p1 <- ggplot(temp, aes(x = group, y = tpm, fill=group)) +
  geom_bar(stat = "summary",fun=mean,position="dodge",width =0.8,show.legend = F,size=2)+ #绘制柱状图
  geom_point(show.legend = F,position = position_jitter(width = 0.1))+
  stat_summary(geom = "errorbar",fun.data = 'mean_sdl', width = 0.3,show.legend = F)+#误差棒
  labs(x=NULL,y=paste0(gene_name," tpm"))+#标题
  theme_prism(palette = "floral",
              base_fontface = "plain", # 字体样式，可选 bold, plain, italic
              base_family = "sans", # 字体格式，可选 serif, sans, mono, Arial等
              base_size = 16,  # 图形的字体大小
              base_line_size = 0.8, # 坐标轴的粗细
              axis_text_angle = 0)+ # 可选值有 0，45，90，270
   scale_fill_manual(values = c("siNC" = "#DB5C25", "siM3" = "#F3B747", "siVirma" = "#649541"))+
  theme(plot.title = element_text(size=16,hjust = -0.5))
  #scale_color_manual(values = c("0h" = "#c6a46b", "4h" = "#a4a4ba", "12h" = "#92adc1"))
  #scale_color_manual(values = c("0h" = "#ecc37f", "4h" = "#c5c5e0", "12h" = "#aecfe7"))
  #scale_fill_prism(palette = "floral")#使用ggprism包修改颜色
  print(p1)
}

dir.create("08_marker")
pdf("08_marker/01_APA_barplot.pdf",width = 3.5,height = 4)
for (i in marker_APA[marker_APA %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
tt_barplot("Gapdh")
tt_barplot("Actb")
dev.off()

pdf("08_marker/02_toti_barplot.pdf",width = 3.5,height = 4)
for (i in marker_toti[marker_toti %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/03_pluri_barplot.pdf",width = 3.5,height = 4)
for (i in marker_pluri[marker_pluri %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/04_TE_TSC_barplot.pdf",width = 3.5,height = 4)
for (i in marker_TE_TSC[marker_TE_TSC %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/05_PrE_XEN_barplot.pdf",width = 3.5,height = 4)
for (i in marker_PrE_XEN[marker_PrE_XEN %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/06_APAperturb_barplot.pdf",width = 3.5,height = 4)
for (i in marker_APAperturb[marker_APAperturb %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
tt_barplot("Gapdh")
tt_barplot("Actb")
dev.off()

```

```{r marker heatmap}
group <- c("toti","pluri","PrE_XEN","TE_TSC","APAperturb")

for (i in group){
  temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% get(paste0("marker_",i)),c(1,2,5:6)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0.2,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/08_heatmap_cluster_col_",i,".pdf"))
heatmap <- draw(heatmap)
dev.off()

}

temp <- c("Zscan4f","Dysf","Gpx3","Tcf7l1","Emp3","Cdkn1a","Gm21761","Lamb1","Sox17","Pdgfra","Dab2","Piwil2","Gata6")
  temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% temp,c(1,2,5:6)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0.2,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/08_heatmap_cluster_col_Virma.pdf"))
heatmap <- draw(heatmap)
dev.off()
```

## DESeq2
### PCA
```{r create dir}
dir.create("03_PCA")
```

```{r PCA - all gene}

meta_data 
colnames(express_matrix)

dds <- DESeqDataSetFromMatrix(countData = express_matrix,colData = meta_data,design = ~ stage)

#pca plot

rlog <- rlog(dds,blind = FALSE)

pcaData <- plotPCA(rlog,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA rlog")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/01_allgene_rlog.pdf",width = 8,height = 7)
print(p1)
dev.off()

vst <- vst(dds,blind = FALSE)

pcaData <- plotPCA(vst,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA vst")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/01_allgene_vst.pdf",width = 8,height = 7)
print(p1)
dev.off()
```

```{r PCA - marker gene}

meta_data 
colnames(express_matrix)

dds <- DESeqDataSetFromMatrix(countData = express_matrix[marker_all,],colData = meta_data,design = ~ stage)

#pca plot

rlog <- rlog(dds,blind = FALSE)

pcaData <- plotPCA(rlog,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA rlog")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/02_allmarker_rlog.pdf",width = 8,height = 7)
print(p1)
dev.off()
```

### for DEG analysis
```{r create dds object}

dds <- DESeqDataSetFromMatrix(countData = express_matrix_filter10,colData = meta_data,design = ~ stage)

dir.create("04_DEG_result")
dir.create("05_DEG_heatmap")
dir.create("06_DEG_volcano")
```

```{r DEG analysis}

#DEG
dds <- DESeq(dds)
resultsNames(dds)

res_siNC_siM3_1 <- tt_DEG_result(dds,"siNC","siM3_1","04_DEG_result")
res_siNC_siM3_2 <- tt_DEG_result(dds,"siNC","siM3_2","04_DEG_result")
res_siNC_siVirma <- tt_DEG_result(dds,"siNC","siVirma","04_DEG_result")

```

## filter1
```{r DEG result filter1}
#filter1

res_siNC_siM3_1_filter_1 <- tt_DEG_filter(res_siNC_siM3_1,"siNC","siM3_1","04_DEG_result",lfcThreshold = 1)
res_siNC_siM3_2_filter_1 <- tt_DEG_filter(res_siNC_siM3_2,"siNC","siM3_2","04_DEG_result",lfcThreshold = 1)
res_siNC_siVirma_filter_1 <- tt_DEG_filter(res_siNC_siVirma,"siNC","siVirma","04_DEG_result",lfcThreshold = 1)

venn.diagram(x=list(M3_1=read.table("04_DEG_result/filter_1/res_siNC_siM3_1down_genename.txt")$V1,M3_2=read.table("04_DEG_result/filter_1/res_siNC_siM3_2down_genename.txt")$V1),filename = "04_DEG_result/filter_1/venn_M3_1_2.png",imagetype = "png")

```

```{r DEG heatmap filter1}

tt_DEG_heatmap(res_siNC_siM3_filter_1,"siNC","siM3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)
tt_DEG_heatmap(res_siNC_siVirma_filter_1,"siNC","siVirma",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)

### cluster col
tt_DEG_heatmap(res_siNC_siM3_filter_1,"siNC","siM3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1,cluster_columns = T,name_suffix = "_cluster_col")
tt_DEG_heatmap(res_siNC_siVirma_filter_1,"siNC","siVirma",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1,cluster_columns = T,name_suffix = "_cluster_col")

```

```{r DEG volcano filter1}
tt_DEG_volcano(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_siNC_siVirma,"siNC","siVirma","06_DEG_volcano/",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

tt_DEG_volcano_mark(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siVirma,"siNC","siVirma","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_toti,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_toti")
```

```{r DEG GO KEGG filter1}

dir.create("07_DEG_GO")

sn <- c("siNC","siM3","siVirma")
for (i in sn[1]){
  for (j in sn[2:3]){
    if (exists(paste0("res_",i,"_",j,"_filter_1"))){
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_1")))[get(paste0("res_",i,"_",j,"_filter_1"))$log2FoldChange>0],groupname = paste0("res_",i,"_",j,"_filter_1_up"),filedir = "07_DEG_GO/")
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_1")))[get(paste0("res_",i,"_",j,"_filter_1"))$log2FoldChange<0],groupname = paste0("res_",i,"_",j,"_filter_1_down"),filedir = "07_DEG_GO/")
    }
  }
}

```

## filter058
```{r DEG result filter058}

res_siNC_siM3_1_filter_058 <- tt_DEG_filter(res_siNC_siM3_1,"siNC","siM3_1","04_DEG_result",lfcThreshold = 0.58)

res_siNC_siM3_2_filter_058 <- tt_DEG_filter(res_siNC_siM3_2,"siNC","siM3_2","04_DEG_result",lfcThreshold = 0.58)

res_siNC_siVirma_filter_058 <- tt_DEG_filter(res_siNC_siVirma,"siNC","siVirma","04_DEG_result",lfcThreshold = 0.58)

```

```{r DEG heatmap filter058}

tt_DEG_heatmap(res_siNC_siM3_filter_058,"siNC","siM3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 0.58)

### cluster col
tt_DEG_heatmap(res_siNC_siM3_filter_058,"siNC","siM3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 0.58,cluster_columns = T,name_suffix = "_cluster_col")

```

```{r DEG volcano filter058}
tt_DEG_volcano(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =0.58,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

tt_DEG_volcano_mark(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =0.58,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siM3,"siNC","siM3","06_DEG_volcano/",lfcThreshold =0.58,label_genes=marker_toti,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_toti")
```

```{r DEG GO KEGG filter058}

for (i in sn[1]){
  for (j in sn[2]){
    if (exists(paste0("res_",i,"_",j,"_filter_058"))){
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_058")))[get(paste0("res_",i,"_",j,"_filter_058"))$log2FoldChange>0],groupname = paste0("res_",i,"_",j,"_filter_058_up"),filedir = "07_DEG_GO/")
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_058")))[get(paste0("res_",i,"_",j,"_filter_058"))$log2FoldChange<0],groupname = paste0("res_",i,"_",j,"_filter_058_down"),filedir = "07_DEG_GO/")
    }
  }
}

```

```{r marker barplot}
dir.create("08_marker")

tpm_matrix[rownames(tpm_matrix) %in% marker_APA,]

pdf("08_marker/01_APA_barplot.pdf",width = 6,height = 4)
for (i in marker_APA[marker_APA %in% rownames(tpm_matrix)]){
  barplot(tpm_matrix[i,],ylab=i)
}
barplot(tpm_matrix["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/02_toti_barplot.pdf",width = 6,height = 4)
for (i in marker_toti[marker_toti %in% rownames(tpm_matrix)]){
  barplot(tpm_matrix[i,],ylab=i)
}
barplot(tpm_matrix["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/03_pluri_barplot.pdf",width = 6,height = 4)
for (i in marker_pluri[marker_pluri %in% rownames(tpm_matrix)]){
  barplot(tpm_matrix[i,],ylab=i)
}
barplot(tpm_matrix["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/04_TE_TSC_barplot.pdf",width = 6,height = 4)
for (i in marker_TE_TSC[marker_TE_TSC %in% rownames(tpm_matrix)]){
  barplot(tpm_matrix[i,],ylab=i)
}
barplot(tpm_matrix["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/05_PrE_XEN_barplot.pdf",width = 6,height = 4)
for (i in marker_PrE_XEN[marker_PrE_XEN %in% rownames(tpm_matrix)]){
  barplot(tpm_matrix[i,],ylab=i)
}
barplot(tpm_matrix["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix["Actb",],ylab="Actb")
dev.off()
```

```{r marker barplot p0p5p10rp2}

tpm_matrix_p0p5p10rp2 <- read.table("../01_p0p5p10rp2/02_express_matrix/tpm_matrix.txt")
tpm_matrix_p0p5p10rp2_siVirma <- as.matrix(cbind(tpm_matrix_p0p5p10rp2,tpm_matrix))

pdf("08_marker/01_APA_barplot_p0p5p10rp2.pdf",width = 6,height = 6)
for (i in marker_APA[marker_APA %in% rownames(tpm_matrix_p0p5p10rp2_siVirma)]){
  barplot(tpm_matrix_p0p5p10rp2_siVirma[i,],ylab=i)
}
barplot(tpm_matrix_p0p5p10rp2_siVirma["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix_p0p5p10rp2_siVirma["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/02_toti_barplot_p0p5p10rp2.pdf",width = 6,height = 4)
for (i in marker_toti[marker_toti %in% rownames(tpm_matrix_p0p5p10rp2_siVirma)]){
  barplot(tpm_matrix_p0p5p10rp2_siVirma[i,],ylab=i)
}
barplot(tpm_matrix_p0p5p10rp2_siVirma["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix_p0p5p10rp2_siVirma["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/03_pluri_barplot_p0p5p10rp2.pdf",width = 6,height = 4)
for (i in marker_pluri[marker_pluri %in% rownames(tpm_matrix_p0p5p10rp2_siVirma)]){
  barplot(tpm_matrix_p0p5p10rp2_siVirma[i,],ylab=i)
}
barplot(tpm_matrix_p0p5p10rp2_siVirma["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix_p0p5p10rp2_siVirma["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/04_TE_TSC_barplot_p0p5p10rp2.pdf",width = 6,height = 4)
for (i in marker_TE_TSC[marker_TE_TSC %in% rownames(tpm_matrix_p0p5p10rp2_siVirma)]){
  barplot(tpm_matrix_p0p5p10rp2_siVirma[i,],ylab=i)
}
barplot(tpm_matrix_p0p5p10rp2_siVirma["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix_p0p5p10rp2_siVirma["Actb",],ylab="Actb")
dev.off()

pdf("08_marker/05_PrE_XEN_barplot_p0p5p10rp2.pdf",width = 6,height = 4)
for (i in marker_PrE_XEN[marker_PrE_XEN %in% rownames(tpm_matrix_p0p5p10rp2_siVirma)]){
  barplot(tpm_matrix_p0p5p10rp2_siVirma[i,],ylab=i)
}
barplot(tpm_matrix_p0p5p10rp2_siVirma["Gapdh",],ylab="Gapdh")
barplot(tpm_matrix_p0p5p10rp2_siVirma["Actb",],ylab="Actb")
dev.off()
```

```{r marker_heatmap}
group <- c("toti","pluri","XEN","TE","2cell_1","2cell_2","4cell","morula","ICM_EPI")

for (i in group){
  heatmap <- Heatmap(matrix = t(scale(t(tpm_DEG_mean[rownames(tpm_DEG_mean) %in% get(paste0("genes_",i)),]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = T,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("07_marker/heatmap_cluster_col_",i,".pdf"))
heatmap <- draw(heatmap)
dev.off()

}

heatmap <- Heatmap(matrix = t(scale(t(tpm_DEG_mean[c(genes_2cell_1,genes_2cell_2,genes_4cell,genes_morula,genes_ICM_EPI),]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows =T,cluster_columns = T,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("07_marker/heatmap_cluster_col_stage.pdf"))
heatmap <- draw(heatmap)
dev.off()

dir.create("07_marker/marker_all_km")

for (i in 1:20){
  heatmap <- Heatmap(matrix = t(scale(t(tpm_DEG_mean[genes_marker,]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows =T,cluster_columns = T,
                                width = unit(4,'inches'),
                   row_km = i,
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("07_marker/marker_all_km/heatmap_cluster_col_marker_km",i,".pdf"),height = 20)
heatmap <- draw(heatmap)
dev.off()
}

```

```{r gsea siM3_1}
dir.create("08_marker_gsea")

## ribosome
Ribosome_genes <- read.table("../../00_gene_set/CC_Ribosome")$V1

msigdb <- data.frame(term=rep("Ribosome",length(Ribosome_genes)),
                     gene=Ribosome_genes)

pdf("08_marker_gsea/gsea_ribosome_siM3_1.pdf",width = 5)
res_siNC_siM3_1_list <- res_siNC_siM3_1$log2FoldChange

names(res_siNC_siM3_1_list) <- rownames(res_siNC_siM3_1)

res_siNC_siM3_1_list <- sort(res_siNC_siM3_1_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_1",pvalue_table = T,base_size = 10)


dev.off()

## ribosome_biogenesis
ribosome_biogenesis_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/ribosome_biogenesis")$V1

msigdb <- data.frame(term=c(rep("ribosome_biogenesis",length(ribosome_biogenesis_genes))),
                     gene=c(ribosome_biogenesis_genes))


pdf("08_marker_gsea/gsea_ribosome_biogenesis_siM3_1.pdf",width = 5)
res_siNC_siM3_1_list <- res_siNC_siM3_1$log2FoldChange

names(res_siNC_siM3_1_list) <- rownames(res_siNC_siM3_1)

res_siNC_siM3_1_list <- sort(res_siNC_siM3_1_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_1",pvalue_table = T,base_size = 10)


dev.off()

## mito
mitochondrial_protein_containing_complex_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrial_protein_containing_complex")$V1

mitochondrion_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrion_organization")$V1

msigdb <- data.frame(term=c(rep("mitochondrial_protein_complex",length(mitochondrial_protein_containing_complex_genes)),
                            rep("mitochondrion_organization",length(mitochondrion_organization_genes))),
                     gene=c(mitochondrial_protein_containing_complex_genes,mitochondrion_organization_genes))


pdf("08_marker_gsea/gsea_mitochondrion_siM3_1.pdf",width = 5)
res_siNC_siM3_1_list <- res_siNC_siM3_1$log2FoldChange

names(res_siNC_siM3_1_list) <- rownames(res_siNC_siM3_1)

res_siNC_siM3_1_list <- sort(res_siNC_siM3_1_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_1",pvalue_table = T,base_size = 10)


dev.off()

## extracellular 
extracellular_matrix_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix_organization")$V1

extracellular_matrix_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix")$V1

msigdb <- data.frame(term=c(rep("extracellular_matrix_organization",length(extracellular_matrix_organization_genes)),
                            rep("extracellular_matrix",length(extracellular_matrix_genes))),
                     gene=c(extracellular_matrix_organization_genes,extracellular_matrix_genes))


pdf("08_marker_gsea/gsea_extracellular_matrix_siM3_1.pdf",width = 5)
res_siNC_siM3_1_list <- res_siNC_siM3_1$log2FoldChange

names(res_siNC_siM3_1_list) <- rownames(res_siNC_siM3_1)

res_siNC_siM3_1_list <- sort(res_siNC_siM3_1_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:2,
          title="siNC_siM3_1",pvalue_table = T,base_size = 10)


dev.off()


extracellular_matrix_intersect_genes <- intersect(extracellular_matrix_genes,extracellular_matrix_organization_genes)

msigdb <- data.frame(term=c(rep("extracellular_matrix_intersect",length(extracellular_matrix_intersect_genes))),
                     gene=c(extracellular_matrix_intersect_genes))


pdf("08_marker_gsea/gsea_extracellular_matrix_intersect_siM3_1.pdf",width = 5)
res_siNC_siM3_1_list <- res_siNC_siM3_1$log2FoldChange

names(res_siNC_siM3_1_list) <- rownames(res_siNC_siM3_1)

res_siNC_siM3_1_list <- sort(res_siNC_siM3_1_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_1",pvalue_table = T,base_size = 10)


dev.off()

```

```{r gsea siM3_2}
dir.create("08_marker_gsea")

## ribosome
Ribosome_genes <- read.table("../../00_gene_set/CC_Ribosome")$V1

msigdb <- data.frame(term=rep("Ribosome",length(Ribosome_genes)),
                     gene=Ribosome_genes)

pdf("08_marker_gsea/gsea_ribosome_siM3_2.pdf",width = 5)
res_siNC_siM3_2_list <- res_siNC_siM3_2$log2FoldChange

names(res_siNC_siM3_2_list) <- rownames(res_siNC_siM3_2)

res_siNC_siM3_2_list <- sort(res_siNC_siM3_2_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_2_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_2",pvalue_table = T,base_size = 10)


dev.off()

## ribosome_biogenesis
ribosome_biogenesis_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/ribosome_biogenesis")$V1

msigdb <- data.frame(term=c(rep("ribosome_biogenesis",length(ribosome_biogenesis_genes))),
                     gene=c(ribosome_biogenesis_genes))


pdf("08_marker_gsea/gsea_ribosome_biogenesis_siM3_2.pdf",width = 5)
res_siNC_siM3_2_list <- res_siNC_siM3_2$log2FoldChange

names(res_siNC_siM3_2_list) <- rownames(res_siNC_siM3_2)

res_siNC_siM3_2_list <- sort(res_siNC_siM3_2_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_2_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_2",pvalue_table = T,base_size = 10)


dev.off()

## mito
mitochondrial_protein_containing_complex_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrial_protein_containing_complex")$V1

mitochondrion_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrion_organization")$V1

msigdb <- data.frame(term=c(rep("mitochondrial_protein_complex",length(mitochondrial_protein_containing_complex_genes)),
                            rep("mitochondrion_organization",length(mitochondrion_organization_genes))),
                     gene=c(mitochondrial_protein_containing_complex_genes,mitochondrion_organization_genes))


pdf("08_marker_gsea/gsea_mitochondrion_siM3_2.pdf",width = 5)
res_siNC_siM3_2_list <- res_siNC_siM3_2$log2FoldChange

names(res_siNC_siM3_2_list) <- rownames(res_siNC_siM3_2)

res_siNC_siM3_2_list <- sort(res_siNC_siM3_2_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_2_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_2",pvalue_table = T,base_size = 10)


dev.off()

## extracellular 
extracellular_matrix_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix_organization")$V1

extracellular_matrix_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix")$V1

msigdb <- data.frame(term=c(rep("extracellular_matrix_organization",length(extracellular_matrix_organization_genes)),
                            rep("extracellular_matrix",length(extracellular_matrix_genes))),
                     gene=c(extracellular_matrix_organization_genes,extracellular_matrix_genes))


pdf("08_marker_gsea/gsea_extracellular_matrix_siM3_2.pdf",width = 5)
res_siNC_siM3_2_list <- res_siNC_siM3_2$log2FoldChange

names(res_siNC_siM3_2_list) <- rownames(res_siNC_siM3_2)

res_siNC_siM3_2_list <- sort(res_siNC_siM3_2_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_2_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:2,
          title="siNC_siM3_2",pvalue_table = T,base_size = 10)


dev.off()


extracellular_matrix_intersect_genes <- intersect(extracellular_matrix_genes,extracellular_matrix_organization_genes)

msigdb <- data.frame(term=c(rep("extracellular_matrix_intersect",length(extracellular_matrix_intersect_genes))),
                     gene=c(extracellular_matrix_intersect_genes))


pdf("08_marker_gsea/gsea_extracellular_matrix_intersect_siM3_2.pdf",width = 5)
res_siNC_siM3_2_list <- res_siNC_siM3_2$log2FoldChange

names(res_siNC_siM3_2_list) <- rownames(res_siNC_siM3_2)

res_siNC_siM3_2_list <- sort(res_siNC_siM3_2_list,decreasing = T)


gsea <- GSEA(res_siNC_siM3_2_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1,
          title="siNC_siM3_2",pvalue_table = T,base_size = 10)


dev.off()

```

```{r DEG overlap siM3 siNust21}
VennDiagram::venn.diagram(x=list(siM3_1_down=read.table("04_DEG_result/filter_0.58/res_siNC_siM3_1down_genename.txt")$V1,
                                 siNudt21_1_down=read.table("../03_p6_siNudt21/04_DEG_result/filter_0.58/res_siNC_siNudt21_1down_genename.txt")$V1),
                          filename = "04_DEG_result/filter_0.58/venn_siM3_1_siNudt21_1_down.png",
                          imagetype = "png")

VennDiagram::venn.diagram(x=list(siM3_1_up=read.table("04_DEG_result/filter_0.58/res_siNC_siM3_1up_genename.txt")$V1,
                                 siNudt21_1_up=read.table("../03_p6_siNudt21/04_DEG_result/filter_0.58/res_siNC_siNudt21_1up_genename.txt")$V1),
                          filename = "04_DEG_result/filter_0.58/venn_siM3_1_siNudt21_1_up.png",
                          imagetype = "png")

VennDiagram::venn.diagram(x=list(siM3_2_down=read.table("04_DEG_result/filter_0.58/res_siNC_siM3_2down_genename.txt")$V1,
                                 siNudt21_1_down=read.table("../03_p6_siNudt21/04_DEG_result/filter_0.58/res_siNC_siNudt21_1down_genename.txt")$V1),
                          filename = "04_DEG_result/filter_0.58/venn_siM3_2_siNudt21_1_down.png",
                          imagetype = "png")

VennDiagram::venn.diagram(x=list(siM3_2_up=read.table("04_DEG_result/filter_0.58/res_siNC_siM3_2up_genename.txt")$V1,
                                 siNudt21_1_up=read.table("../03_p6_siNudt21/04_DEG_result/filter_0.58/res_siNC_siNudt21_1up_genename.txt")$V1),
                          filename = "04_DEG_result/filter_0.58/venn_siM3_2_siNudt21_1_up.png",
                          imagetype = "png")


```

```{r DEG top 500}

dir.create("04_DEG_result/top500")
res_siNC_siM3_1_ft <- subset(as.data.frame(res_siNC_siM3_1),padj < 0.05 )
res_siNC_siM3_1_ft <- res_siNC_siM3_1_ft[order(res_siNC_siM3_1_ft$log2FoldChange,decreasing = T),]

table(res_siNC_siM3_1_ft$log2FoldChange>0)

res_siNC_siM3_1_ft_up500 <- head(res_siNC_siM3_1_ft,500)
res_siNC_siM3_1_ft_down500 <- tail(res_siNC_siM3_1_ft,500)

tt_wt(res_siNC_siM3_1_ft_up500,"04_DEG_result/top500/res_siNC_siM3_1_ft_up500.txt",row.names = T,col.names = T)
tt_wt(res_siNC_siM3_1_ft_down500,"04_DEG_result/top500/res_siNC_siM3_1_ft_down500.txt",row.names = T,col.names = T)

tt_wt(rownames(res_siNC_siM3_1_ft_up500),"04_DEG_result/top500/res_siNC_siM3_1_ft_up500_gene.txt")
tt_wt(rownames(res_siNC_siM3_1_ft_down500),"04_DEG_result/top500/res_siNC_siM3_1_ft_down500_gene.txt")

tt_enrichGO(rownames(res_siNC_siM3_1_ft_up500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siM3_1_ft_up500")

tt_enrichGO(rownames(res_siNC_siM3_1_ft_down500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siM3_1_ft_down500")

dir.create("04_DEG_result/top400")
res_siNC_siM3_1_ft_up400 <- head(res_siNC_siM3_1_ft,400)
res_siNC_siM3_1_ft_down400 <- tail(res_siNC_siM3_1_ft,400)

tt_wt(res_siNC_siM3_1_ft_up400,"04_DEG_result/top400/res_siNC_siM3_1_ft_up400.txt",row.names = T,col.names = T)
tt_wt(res_siNC_siM3_1_ft_down400,"04_DEG_result/top400/res_siNC_siM3_1_ft_down400.txt",row.names = T,col.names = T)

tt_wt(rownames(res_siNC_siM3_1_ft_up400),"04_DEG_result/top400/res_siNC_siM3_1_ft_up400_gene.txt")
tt_wt(rownames(res_siNC_siM3_1_ft_down400),"04_DEG_result/top400/res_siNC_siM3_1_ft_down400_gene.txt")

tt_enrichGO(rownames(res_siNC_siM3_1_ft_up400),filedir = "04_DEG_result/top400",groupname = "res_siNC_siM3_1_ft_up400")

tt_enrichGO(rownames(res_siNC_siM3_1_ft_down400),filedir = "04_DEG_result/top400",groupname = "res_siNC_siM3_1_ft_down400")

### siM3_2
res_siNC_siM3_2_ft <- subset(as.data.frame(res_siNC_siM3_2),padj < 0.05 )
res_siNC_siM3_2_ft <- res_siNC_siM3_2_ft[order(res_siNC_siM3_2_ft$log2FoldChange,decreasing = T),]

table(res_siNC_siM3_2_ft$log2FoldChange>0)

res_siNC_siM3_2_ft_up500 <- head(res_siNC_siM3_2_ft,500)
res_siNC_siM3_2_ft_down500 <- tail(res_siNC_siM3_2_ft,500)

tt_wt(res_siNC_siM3_2_ft_up500,"04_DEG_result/top500/res_siNC_siM3_2_ft_up500.txt",row.names = T,col.names = T)
tt_wt(res_siNC_siM3_2_ft_down500,"04_DEG_result/top500/res_siNC_siM3_2_ft_down500.txt",row.names = T,col.names = T)

tt_wt(rownames(res_siNC_siM3_2_ft_up500),"04_DEG_result/top500/res_siNC_siM3_2_ft_up500_gene.txt")
tt_wt(rownames(res_siNC_siM3_2_ft_down500),"04_DEG_result/top500/res_siNC_siM3_2_ft_down500_gene.txt")

tt_enrichGO(rownames(res_siNC_siM3_2_ft_up500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siM3_2_ft_up500")

tt_enrichGO(rownames(res_siNC_siM3_2_ft_down500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siM3_2_ft_down500")

### top 400
res_siNC_siM3_2_ft_up400 <- head(res_siNC_siM3_2_ft,400)
res_siNC_siM3_2_ft_down400 <- tail(res_siNC_siM3_2_ft,400)

tt_wt(res_siNC_siM3_2_ft_up400,"04_DEG_result/top400/res_siNC_siM3_2_ft_up400.txt",row.names = T,col.names = T)
tt_wt(res_siNC_siM3_2_ft_down400,"04_DEG_result/top400/res_siNC_siM3_2_ft_down400.txt",row.names = T,col.names = T)

tt_wt(rownames(res_siNC_siM3_2_ft_up400),"04_DEG_result/top400/res_siNC_siM3_2_ft_up400_gene.txt")
tt_wt(rownames(res_siNC_siM3_2_ft_down400),"04_DEG_result/top400/res_siNC_siM3_2_ft_down400_gene.txt")

tt_enrichGO(rownames(res_siNC_siM3_2_ft_up400),filedir = "04_DEG_result/top400",groupname = "res_siNC_siM3_2_ft_up400")

tt_enrichGO(rownames(res_siNC_siM3_2_ft_down400),filedir = "04_DEG_result/top400",groupname = "res_siNC_siM3_2_ft_down400")

venn.diagram(x=list(siM3_1=rownames(res_siNC_siM3_1_ft_up500),siNudt21_1=read.table("../03_p6_siNudt21/04_DEG_result/top500/res_siNC_siNudt21_1_ft_up500_gene.txt")$V1),
             imagetype = "png",filename = "04_DEG_result/top500/siM3_1_siNudt21_1_up.png")

venn.diagram(x=list(siM3_1=rownames(res_siNC_siM3_1_ft_down500),siNudt21_1=read.table("../03_p6_siNudt21/04_DEG_result/top500/res_siNC_siNudt21_1_ft_down500_gene.txt")$V1),
             imagetype = "png",filename = "04_DEG_result/top500/siM3_1_siNudt21_1_down.png")

venn.diagram(x=list(siM3_2_up=rownames(res_siNC_siM3_2_ft_up500),siNudt21_1_up=read.table("../03_p6_siNudt21/04_DEG_result/top500/res_siNC_siNudt21_1_ft_up500_gene.txt")$V1),
             imagetype = "png",filename = "04_DEG_result/top500/siM3_2_siNudt21_1_up.png")

venn.diagram(x=list(siM3_2_down=rownames(res_siNC_siM3_2_ft_down500),siNudt21_1_down=read.table("../03_p6_siNudt21/04_DEG_result/top500/res_siNC_siNudt21_1_ft_down500_gene.txt")$V1),
             imagetype = "png",filename = "04_DEG_result/top500/siM3_2_siNudt21_1_down.png")

```


















