---
title: "r02_DEG_mRNA_all_batch"
author: "Tang Li"
date: '2022-10-16'
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(DESeq2)
library(GEOquery)
library(GenomicFeatures)
library(BiocParallel)
library(GenomicAlignments)
library(rtracklayer)
library(NMF)
library(parallel)
library(Rsubread)
library(RUVSeq)
library(stringr)
library(data.table)
library(ggplot2)
library(ggprism)
library(RColorBrewer)
library(ttFunctions)
library(ggthemes)
library(ggsci)
library(ggpubr)
library(ComplexHeatmap)
library(sva)
options(stringsAsFactors = FALSE)
library(ggrepel)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(clusterProfiler)
library(VennDiagram)
library(org.Hs.eg.db)
library(biomaRt)
library(enrichplot)

# ~/Data/09_PseudoU/04_aging_mRNA/05_mRNA_expression/01_all_batch/

work_dir <- "~/Data/09_PseudoU/04_aging_mRNA/05_mRNA_expression/01_all_batch/"
require("knitr")
opts_knit$set(root.dir = file.path(work_dir))

```

## featurecount

```{r}

fc_result_count <- read.table("../../04_RS_DEG/01_featureCounts/express_matrix_count_rowname_modified.txt")
fc_result_annotation <- read.table("../../04_RS_DEG/01_featureCounts/express_matrix_annotation_rowname_modified.txt")

```

```{r betweenLaneNormalization & expression filter10}

colnames(fc_result_count)
sample_name <- paste(rep(c("IC","IR","IC_shCtrl","IC_shDKC1","IR_shCtrl","IR_shDKC1","P12","P16","P13_shCtrl","P13_shDKC1"),each=2),
                      rep(c("1","2"),times=10),
                      sep = "_")
express_matrix <- fc_result_count
colnames(express_matrix) <- sample_name

batch <- c(rep("IR",4),rep("shDKC1",8),rep("IR",4),rep("shDKC1",4))
# #group <- rep(c("P12","P16","P13_shCtrl","P13_shDKC1"),each=2)
express_sva <- ComBat_seq(as.matrix(express_matrix),batch = batch)
# #express_sva2 <- ComBat_seq(as.matrix(express_matrix),batch = batch,group = group)

meta_data <- data.frame(rep = rep(c("rep1","rep2"),times=10),
                        stage = rep(c("IC","IR","IC_shCtrl","IC_shDKC1","IR_shCtrl","IR_shDKC1","P12","P16","P13_shCtrl","P13_shDKC1"),each=2),
                        row.names = sample_name,
                        sample_name = sample_name,
                        stringsAsFactors = TRUE)
meta_data

x <- meta_data$stage
set <- newSeqExpressionSet(as.matrix(express_sva),
                           phenoData = data.frame(x, row.names=colnames(express_matrix)))
set

colors <- brewer.pal(18, "BrBG")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

set <- betweenLaneNormalization(set, which="upper")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

express_matrix <- set@assayData$normalizedCounts

dir.create("02_express_matrix")
tt_wt(express_matrix,"02_express_matrix/express_matrix.txt",row.names=T,col.names = T)
# 对表达量进行筛选
filter <- rowSums(express_matrix>5)>=2
table(filter)
express_matrix_filter5 <- express_matrix[filter,]

colnames(express_matrix_filter5)
tt_wt(express_matrix_filter5,"02_express_matrix/express_matrix_filter5.txt",row.names=T,col.names = T)
```

```{r get tpm_matrix}
#convert to TPM

tpm_matrix <- do.call(cbind,base::lapply(colnames(express_matrix),FUN = function(x){
  counts <- express_matrix[,x]
  effLen <- fc_result_annotation[rownames(express_matrix),"Length"]
  rate <- log(counts) - log(effLen)
  denom <- log(sum(exp(rate)))
  return(exp(rate-denom+log(1e6)))
}))

rownames(tpm_matrix) <- rownames(express_matrix)
colnames(tpm_matrix) <- colnames(express_matrix)
table(colSums(tpm_matrix))

write.table(tpm_matrix,file="02_express_matrix/tpm_matrix.txt",quote = F,sep = "\t")
```

## DESeq2
```{r create dds object and plot pca}

meta_data 
colnames(express_matrix)
sample_name

dds <- DESeqDataSetFromMatrix(countData = express_matrix_filter5,colData = meta_data,design = ~ stage)

```

```{r DEG analysis}
dir.create("04_DEG_result")
dir.create("05_DEG_heatmap")
dir.create("06_DEG_volcano")
dir.create("07_DEG_GO")

#DEG
dds <- DESeq(dds)
resultsNames(dds)

res_P12_P16 <- tt_DEG_result(dds,"P12","P16","04_DEG_result")
res_P13_shDKC1 <- tt_DEG_result(dds,"P13_shCtrl","P13_shDKC1","04_DEG_result")

```


```{r DEG result filter1}
#filter1
#### 

res_P12_P16_filter_1 <- tt_DEG_filter(res_P12_P16,"P12","P16","04_DEG_result",lfcThreshold = 1)
res_P13_shDKC1_filter_1 <- tt_DEG_filter(res_P13_shDKC1,"P13_shCtrl","P13_shDKC1","04_DEG_result",lfcThreshold = 1)

tt_DEG_heatmap(res_P12_P16_filter_1,"P12","P16",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)
tt_DEG_heatmap(res_P13_shDKC1_filter_1,"P13_shCtrl","P13_shDKC1",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)


tt_DEG_volcano(res_P12_P16,"P12","P16",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_P13_shDKC1,"P13_shCtrl","P13_shDKC1",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

tt_enrichGO(genelist = rownames(res_P13_shDKC1_filter_1)[res_P13_shDKC1_filter_1$log2FoldChange>0],groupname = "P13_shDKC1_filter1_up",OrgDb = org.Hs.eg.db,filedir = "07_DEG_GO/",width = 8)
tt_enrichGO(genelist = rownames(res_P13_shDKC1_filter_1)[res_P13_shDKC1_filter_1$log2FoldChange<0],groupname = "P13_shDKC1_filter1_down",OrgDb = org.Hs.eg.db,filedir = "07_DEG_GO/",width = 8)

tt_enrichGO(genelist = rownames(res_P12_P16_filter_1)[res_P12_P16_filter_1$log2FoldChange>0],groupname = "P12_P16_filter1_up",OrgDb = org.Hs.eg.db,filedir = "07_DEG_GO/",width = 8)
tt_enrichGO(genelist = rownames(res_P12_P16_filter_1)[res_P12_P16_filter_1$log2FoldChange<0],groupname = "P12_P16_filter1_down",OrgDb = org.Hs.eg.db,filedir = "07_DEG_GO/",width = 8)

```

```{r RS reverse}
intersect(rownames(res_P12_P16[res_P12_P16$log2FoldChange>0.58 & res_P12_P16$padj<0.05,]),rownames(res_P13_shDKC1[res_P13_shDKC1$log2FoldChange< -0.58 & res_P13_shDKC1$padj<0.05,]))

intersect(rownames(res_P12_P16[res_P12_P16$log2FoldChange< -0.58 & res_P12_P16$padj<0.05,]),rownames(res_P13_shDKC1[res_P13_shDKC1$log2FoldChange>0.58 & res_P13_shDKC1$padj<0.05,]))

venn.diagram(x=list(P16_up=rownames(res_P12_P16[res_P12_P16$log2FoldChange>0.58 & res_P12_P16$padj<0.05,]),P13_shDKC1_down=rownames(res_P13_shDKC1[res_P13_shDKC1$log2FoldChange< -0.58 & res_P13_shDKC1$padj<0.05,])),filename = "04_DEG_result/venn_P16_up_P13_shDKC1_down.png",imagetype = "png")

venn.diagram(x=list(P16_down=rownames(res_P12_P16[res_P12_P16$log2FoldChange< -0.58 & res_P12_P16$padj<0.05,]),P13_shDKC1_up=rownames(res_P13_shDKC1[res_P13_shDKC1$log2FoldChange>0.58 & res_P13_shDKC1$padj<0.05,])),filename = "04_DEG_result/venn_P16_down_P13_shDKC1_up.png",imagetype = "png")
```

```{r}
res_IC_IR_shCtrl_clear <- res_IC_IR_shCtrl[!is.na(res_IC_IR_shCtrl$log2FoldChange),]
res_IR_shDKC1_clear <- res_IR_shDKC1[!is.na(res_IR_shDKC1$log2FoldChange),]
Heatmap(t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% c(intersect(rownames(res_IC_IR_shCtrl_filter_1[res_IC_IR_shCtrl_filter_1$log2FoldChange>1,]),rownames(res_IR_shDKC1_filter_1[res_IR_shDKC1_filter_1$log2FoldChange< -1,])),intersect(rownames(res_IC_IR_shCtrl_filter_1[(res_IC_IR_shCtrl_filter_1$log2FoldChange< -1)==TRUE,]),rownames(res_IR_shDKC1_filter_1[(res_IR_shDKC1_filter_1$log2FoldChange>1)==TRUE,]))),]))),
        col=circlize::colorRamp2(c(-1.5,0,1.5),
                               colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))

test <- tpm_matrix[rownames(tpm_matrix) %in% c(intersect(rownames(res_IC_IR_shCtrl_filter_1[res_IC_IR_shCtrl_filter_1$log2FoldChange>1,]),rownames(res_IR_shDKC1_filter_1[res_IR_shDKC1_filter_1$log2FoldChange< -1,])),intersect(rownames(res_IC_IR_shCtrl_filter_1[res_IC_IR_shCtrl_filter_1$log2FoldChange< -1,]),rownames(res_IR_shDKC1_filter_1[res_IR_shDKC1_filter_1$log2FoldChange>1,]))),]

venn::venn(x=list(rownames(res_IC_IR_shCtrl_filter_1),rownames(res_IR_shDKC1_filter_1)))
```

```{r DEG result filter0.58}
#filter1
#### 
lfcThreshold <- 0.58
res_IC_IR_filter_058 <- tt_DEG_filter(res_IC_IR,i = "IC",j="IR",lfcThreshold = lfcThreshold)
res_IC_shDKC1_filter_058 <- tt_DEG_filter(res_IC_shDKC1,i = "IC_shCtrl",j="IC_shDKC1",lfcThreshold =lfcThreshold)
res_IR_shDKC1_filter_058 <- tt_DEG_filter(res_IR_shDKC1,"IR_shCtrl","IR_shDKC1",lfcThreshold =lfcThreshold)
res_IC_IR_shCtrl_filter_058 <- tt_DEG_filter(res_IC_IR_shCtrl,"IC_shCtrl","IR_shCtrl",lfcThreshold =lfcThreshold)
res_P12_P16_filter_058 <- tt_DEG_filter(res_P12_P16,"P12","P16",lfcThreshold =lfcThreshold)
res_P13_shDKC1_filter_058 <- tt_DEG_filter(res_P13_shDKC1,"P13_shCtrl","P13_shDKC1",lfcThreshold =lfcThreshold)

tt_DEG_heatmap(res_IC_IR_filter_058,i = "IC",j="IR",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)
tt_DEG_heatmap(res_IC_shDKC1_filter_058,i = "IC_shCtrl",j="IC_shDKC1",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)
tt_DEG_heatmap(res_IR_shDKC1_filter_058,"IR_shCtrl","IR_shDKC1",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)
tt_DEG_heatmap(res_IC_IR_shCtrl_filter_058,"IC_shCtrl","IR_shCtrl",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)
tt_DEG_heatmap(res_P12_P16_filter_058,"P12","P16",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)
tt_DEG_heatmap(res_P13_shDKC1_filter_058,"P13_shCtrl","P13_shDKC1",tpm_matrix,meta_data,lfcThreshold =lfcThreshold)

tt_DEG_volcano(res_IC_IR,i = "IC",j="IR",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_IC_shDKC1,i = "IC_shCtrl",j="IC_shDKC1",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_IR_shDKC1,"IR_shCtrl","IR_shDKC1",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_IC_IR_shCtrl,"IC_shCtrl","IR_shCtrl",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_P12_P16,"P12","P16",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_P13_shDKC1,"P13_shCtrl","P13_shDKC1",lfcThreshold =lfcThreshold,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

dir.create("05_DEG_GO")
dir.create("05_DEG_GO/filter0.58")
tt_enrichKEGG(genelist = rownames(res_IC_IR_filter_058)[res_IC_IR_filter_058$log2FoldChange>0],groupname = "IC_IR_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",organism = "hsa")

tt_enrichGO(genelist = rownames(res_IC_IR_filter_058)[res_IC_IR_filter_058$log2FoldChange>0],groupname = "IC_IR_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 10)
tt_enrichGO(genelist = rownames(res_IC_IR_filter_058)[res_IC_IR_filter_058$log2FoldChange<0],groupname = "IC_IR_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

tt_enrichGO(genelist = rownames(res_IC_IR_shCtrl_filter_058)[res_IC_IR_shCtrl_filter_058$log2FoldChange>0],groupname = "IC_IR_shCtrl_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)
tt_enrichGO(genelist = rownames(res_IC_IR_shCtrl_filter_058)[res_IC_IR_shCtrl_filter_058$log2FoldChange<0],groupname = "IC_IR_shCtrl_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

tt_enrichGO(genelist = rownames(res_IC_shDKC1_filter_058)[res_IC_shDKC1_filter_058$log2FoldChange>0],groupname = "IC_shDKC1_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)
tt_enrichGO(genelist = rownames(res_IC_shDKC1_filter_058)[res_IC_shDKC1_filter_058$log2FoldChange<0],groupname = "IC_shDKC1_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

tt_enrichGO(genelist = rownames(res_IR_shDKC1_filter_058)[res_IR_shDKC1_filter_058$log2FoldChange>0],groupname = "IR_shDKC1_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 10)
tt_enrichGO(genelist = rownames(res_IR_shDKC1_filter_058)[res_IR_shDKC1_filter_058$log2FoldChange<0],groupname = "IR_shDKC1_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

tt_enrichGO(genelist = rownames(res_P13_shDKC1_filter_058)[res_P13_shDKC1_filter_058$log2FoldChange>0],groupname = "P13_shDKC1_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)
tt_enrichGO(genelist = rownames(res_P13_shDKC1_filter_058)[res_P13_shDKC1_filter_058$log2FoldChange<0],groupname = "P13_shDKC1_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

tt_enrichGO(genelist = rownames(res_P12_P16_filter_058)[res_P12_P16_filter_058$log2FoldChange>0],groupname = "P12_P16_filter1_up",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)
tt_enrichGO(genelist = rownames(res_P12_P16_filter_058)[res_P12_P16_filter_058$log2FoldChange<0],groupname = "P12_P16_filter1_down",OrgDb = org.Hs.eg.db,filedir = "05_DEG_GO/filter0.58",width = 8)

```

```{r reverse}
length(rownames(res_P12_P16)[res_P12_P16$log2FoldChange>0.58])
length(rownames(res_P13_shDKC1)[res_P13_shDKC1$log2FoldChange < -0.58])
length(intersect(rownames(res_P12_P16)[res_P12_P16$log2FoldChange>0.58],rownames(res_P13_shDKC1)[res_P13_shDKC1$log2FoldChange < -0.58]))

length(rownames(res_P12_P16)[res_P12_P16$log2FoldChange>0.58])
length(rownames(res_P13_shDKC1)[res_P13_shDKC1$log2FoldChange >0.58])
length(intersect(rownames(res_P12_P16)[res_P12_P16$log2FoldChange>0.58],rownames(res_P13_shDKC1)[res_P13_shDKC1$log2FoldChange >0.58]))
```

```{r senescense marker from NAR2019 paper}
FAM129A
HIST1H1E
HIST1H1D
HIST1H1A
HIST2H2AB
ITPRIPL1
tpm_matrix["PDL1M1",]

tpm_matrix["CCND3",]

tpm_matrix["PTCHD4",]


gene_anno <- ComplexHeatmap::HeatmapAnnotation(express = filter[rownames(tpm_filter),"express"],which = 'row')
heatmap_IR_diff <- Heatmap(matrix = t(scale(t(tpm_IR_diff_mean))),name="z-score",
                                show_column_names = TRUE,show_row_names=FALSE,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                row_km = 4,
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("05_diff_IR/km_4/heatmap_km4.pdf"))
heatmap_IR_diff <- draw(heatmap_IR_diff)
dev.off()
```

```{r GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE}
GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE <- c("AKT3","MIR543","CDK6","PLK2","SIRT1","ABL1","FBXO5","MIR17","MAP3K3","MIF","YBX1","FZR1","SIRT6","SLC30A10","PTEN","RBL1","BCL6","TBX2","MIR590","TERC","TERF2","TERT","TWIST1","WNT1","ZKSCAN3","HMGA2")
table(GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE %in% rownames(tpm_matrix))
tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,]
dir.create("07_marker_heatmap")
pdf("07_marker_heatmap/GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE.pdf")
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,5:8]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
dev.off()

pdf("07_marker_heatmap/GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE_RS1.pdf")
heatmap_P12_P16 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap_P13_shDKC1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap_P12_P16+heatmap_P13_shDKC1)
draw(heatmap_P13_shDKC1+heatmap_P12_P16)
dev.off()

pdf("07_marker_heatmap/GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE_IR1.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()

pdf("07_marker_heatmap/GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE_IR2.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()

GOBP_CELLULAR_SENESCENCE <- c("AKT3","MIR543","CDK2","CDK6","CDKN1A","ZMPSTE24","CDKN1B","CDKN2A","CDKN2B","CITED2","KAT5","PLK2","NEK6","ZNF277","CGAS","MAPK14","VASH1","PLA2R1","SMC5","SIRT1","MORC3","NUP62","ABL1","ULK3","RSL1D1","FBXO5","MAGEA2B","NSMCE2","H2AX","HLA-G","HMGA1","HRAS","ID2","IGF1R","ING2","KIR2DL4","ARG2","LMNA","ARNTL","MIR10A","MIR146A","MIR17","MIR188","MIR217","MIR22","MIR34A","MAGEA2","MAP3K3","MAP3K5","MIF","MNT","ATM","NPM1","YBX1","OPA1","PAWR","ABI3","FZR1","WNT16","SIRT6","PML","PRMT6","PRELP","SLC30A10","PRKCD","MAPK8","MAPK11","MAPK9","MAPK10","MAP2K1","MAP2K3","MAP2K6","MAP2K7","B2M","ZMIZ1","PTEN","MIR20B","RBL1","BCL6","MAP2K4","BMPR1A","SPI1","SRF","BRCA2","NEK4","TBX2","TBX3","MIR590","TERC","TERF2","TERT","TP53","TWIST1","WNT1","WRN","SMC6","KAT6A","ZKSCAN3","HMGA2","CALR","YPEL3","ECRG4","MAPKAPK5","TP63","PNPT1","DNAJA3","EEF1E1","NUAK1")

GOBP_STRESS_INDUCED_PREMATURE_SENESCENCE <- c("CDKN1A","MAPK14","PLA2R1","SIRT1","ARNTL","WNT16","TP53","MAPKAPK5")
GOBP_REPLICATIVE_SENESCENCE <- c("CDKN1A","CDKN2A","CHEK1","CHEK2","ROMO1","ERCC1","PLA2R1","MIR21","MME","ATM","SERPINE1","WNT16","ATR","TERT","TP53","WRN","CTC1")
GOBP_REGULATION_OF_CELLULAR_SENESCENCE <- c("AKT3","MIR543","CDK6","ZMPSTE24","PLK2","NEK6","ZNF277","CGAS","VASH1","SIRT1","MORC3","ABL1","RSL1D1","FBXO5","HLA-G","ING2","KIR2DL4","ARG2","ARNTL","MIR10A","MIR146A","MIR17","MIR188","MIR217","MIR22","MIR34A","MAP3K3","MIF","YBX1","PAWR","ABI3","FZR1","SIRT6","SLC30A10","B2M","PTEN","MIR20B","RBL1","BCL6","BMPR1A","NEK4","TBX2","MIR590","TERC","TERF2","TERT","TP53","TWIST1","WNT1","ZKSCAN3","HMGA2","YPEL3","PNPT1","EEF1E1","NUAK1")
GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE <- c("CGAS","SIRT1","MORC3","HLA-G","KIR2DL4","ARG2","MIR10A","MIR146A","MIR188","MIR217","MIR22","MIR34A","PAWR","ABI3","B2M","MIR20B","TP53","YPEL3","EEF1E1")

msigdb <- data.frame(term=c(rep("NEGATIVE",length(GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE)),
                            rep("POSITIVE",length(GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE)),
                            rep("REGULATION",length(GOBP_REGULATION_OF_CELLULAR_SENESCENCE)),
                            rep("STRESS_INDUCED",length(GOBP_STRESS_INDUCED_PREMATURE_SENESCENCE)),
                            rep("REPLICATIVE",length(GOBP_REPLICATIVE_SENESCENCE)),
                            rep("SENESCENCE",length(GOBP_CELLULAR_SENESCENCE))),
                     gene=c(GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE,
                            GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE,
                            GOBP_REGULATION_OF_CELLULAR_SENESCENCE,
                            GOBP_STRESS_INDUCED_PREMATURE_SENESCENCE,
                            GOBP_REPLICATIVE_SENESCENCE,
                            GOBP_CELLULAR_SENESCENCE))

dir.create("08_marker_gsea")
############ day10_UP_M3IN

pdf("08_marker_gsea/gsea_senescence_marker.pdf")
res_P12_P16_list <- res_P12_P16$log2FoldChange

names(res_P12_P16_list) <- rownames(res_P12_P16)

res_P12_P16_list <- sort(res_P12_P16_list,decreasing = T)


gsea <- GSEA(res_P12_P16_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="P12_P16",pvalue_table = T,base_size = 10)

res_P13_shDKC1_list <- res_P13_shDKC1$log2FoldChange

names(res_P13_shDKC1_list) <- rownames(res_P13_shDKC1)

res_P13_shDKC1_list <- sort(res_P13_shDKC1_list,decreasing = T)


gsea <- GSEA(res_P13_shDKC1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="P13_shDKC1",pvalue_table = T,base_size = 10)

res_IC_IR_list <- res_IC_IR$log2FoldChange

names(res_IC_IR_list) <- rownames(res_IC_IR)

res_IC_IR_list <- sort(res_IC_IR_list,decreasing = T)


gsea <- GSEA(res_IC_IR_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="IC_IR",pvalue_table = T,base_size = 10)

res_IR_shDKC1_list <- res_IR_shDKC1$log2FoldChange

names(res_IR_shDKC1_list) <- rownames(res_IR_shDKC1)

res_IR_shDKC1_list <- sort(res_IR_shDKC1_list,decreasing = T)


gsea <- GSEA(res_IR_shDKC1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="IR_shDKC1",pvalue_table = T,base_size = 10)

res_IC_shDKC1_list <- res_IC_shDKC1$log2FoldChange

names(res_IC_shDKC1_list) <- rownames(res_IC_shDKC1)

res_IC_shDKC1_list <- sort(res_IC_shDKC1_list,decreasing = T)


gsea <- GSEA(res_IC_shDKC1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="IC_shDKC1",pvalue_table = T,base_size = 10)

res_IC_IR_shCtrl_list <- res_IC_IR_shCtrl$log2FoldChange

names(res_IC_IR_shCtrl_list) <- rownames(res_IC_IR_shCtrl)

res_IC_IR_shCtrl_list <- sort(res_IC_IR_shCtrl_list,decreasing = T)


gsea <- GSEA(res_IC_IR_shCtrl_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

gseaplot2(gsea,geneSetID=1:6,
          title="IC_IR_shCtrl",pvalue_table = T,base_size = 10)

dev.off()

ggsave("08_marker_gsea/P12_P16.pdf")

```

```{r GOBP_REPLICATIVE_SENESCENCE}

table(GOBP_REPLICATIVE_SENESCENCE %in% rownames(tpm_matrix))
tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,]
dir.create("07_marker_heatmap")
pdf("07_marker_heatmap/GOBP_REPLICATIVE_SENESCENCE.pdf")
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,5:8]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
dev.off()

pdf("07_marker_heatmap/GOBP_REPLICATIVE_SENESCENCE_RS1.pdf")
heatmap_P12_P16 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap_P13_shDKC1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap_P12_P16+heatmap_P13_shDKC1)
draw(heatmap_P13_shDKC1+heatmap_P12_P16)
dev.off()

pdf("07_marker_heatmap/GOBP_REPLICATIVE_SENESCENCE_IR1.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()

pdf("07_marker_heatmap/GOBP_REPLICATIVE_SENESCENCE_IR2.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_REPLICATIVE_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()



```

```{r GOBP_CELLULAR_SENESCENCE}

table(GOBP_CELLULAR_SENESCENCE %in% rownames(tpm_matrix))
tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,]
dir.create("07_marker_heatmap")
pdf("07_marker_heatmap/GOBP_CELLULAR_SENESCENCE.pdf")
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,5:8]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
dev.off()

pdf("07_marker_heatmap/GOBP_CELLULAR_SENESCENCE_RS1.pdf")
heatmap_P12_P16 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,13:16]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap_P13_shDKC1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,17:20]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap_P12_P16+heatmap_P13_shDKC1)
draw(heatmap_P13_shDKC1+heatmap_P12_P16)
dev.off()

pdf("07_marker_heatmap/GOBP_CELLULAR_SENESCENCE_IR1.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,1:4]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()

pdf("07_marker_heatmap/GOBP_CELLULAR_SENESCENCE_IR2.pdf")
heatmap1 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,c(5,6,9,10)]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
heatmap2 <- Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% GOBP_CELLULAR_SENESCENCE,9:12]))),name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(2,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))
draw(heatmap1+heatmap2)
draw(heatmap2+heatmap1)

dev.off()



```

```{r site_all_overlap}
site_info_all <- read.delim("~/Data/09_PseudoU/06_aging_pU_SE/04_hisat2_mapping/06_site_filter/04_site_info_final/site_info_anno_merge.txt")

table(GOBP_CELLULAR_SENESCENCE %in% site_info_all$Gene.Name)

```

```{r lfc cluster}
dir.create("06_lfc_rev")
tt_wt(rownames(res_P12_P16[res_P12_P16$log2FoldChange>0.58 & res_P13_shDKC1$log2FoldChange < -0.3,]),"06_lfc_rev/P16_up058_P13_shDKC1_down030.txt")

tt_wt(rownames(res_P12_P16[res_P12_P16$log2FoldChange< -0.58 & res_P13_shDKC1$log2FoldChange >0.3,]),"06_lfc_rev/P16_down058_P13_shDKC1_up030.txt")

tt_wt(rownames(res_IC_IR_shCtrl[res_IC_IR_shCtrl$log2FoldChange>0.58 & res_IR_shDKC1$log2FoldChange < -0.3,]),"06_lfc_rev/IC_IR_shCtrl_up058_IR_shDKC1_down030.txt")

tt_wt(rownames(res_IC_IR_shCtrl[res_IC_IR_shCtrl$log2FoldChange< -0.58 & res_IR_shDKC1$log2FoldChange >0.3,]),"06_lfc_rev/IC_IR_shCtrl_down058_IR_shDKC1_up030.txt")

tt_wt(rownames(res_IC_IR[res_IC_IR$log2FoldChange>0.58 & res_IR_shDKC1$log2FoldChange < -0.3,]),"06_lfc_rev/IC_IR_up058_IR_shDKC1_down030.txt")

tt_wt(rownames(res_IC_IR[res_IC_IR$log2FoldChange< -0.58 & res_IR_shDKC1$log2FoldChange >0.3,]),"06_lfc_rev/IC_IR_down058_IR_shDKC1_up030.txt")

res_lfc_summary <- data.frame(P12_P16=res_P12_P16$log2FoldChange,
                              P13_shDKC1=res_P13_shDKC1$log2FoldChange,
                              IC_IR=res_IC_IR$log2FoldChange,
                              IC_IR_shCtrl=res_IC_IR_shCtrl$log2FoldChange,
                              IC_shDKC1=res_IC_shDKC1$log2FoldChange,
                              IR_shDKC1=res_IR_shDKC1$log2FoldChange)

plot(res_lfc_summary)
ggplot()

table(res_P12_P16$log2FoldChange>0.58 & res_P13_shDKC1$log2FoldChange>0.3)
table(res_P12_P16$log2FoldChange< -0.58 & res_P13_shDKC1$log2FoldChange < -0.58)
table(res_P12_P16$log2FoldChange< -0.58 & res_P13_shDKC1$log2FoldChange>0.58)
```

```{r diff_IR cluster}
dir.create("05_diff_IR")
IR_diff_geneset_filter1 <- c(rownames(res_IC_IR_filter_1),
                       rownames(res_IC_IR_shCtrl_filter_1),
                       rownames(res_IC_shDKC1_filter_1),
                       rownames(res_IR_shDKC1_filter_1))

IR_diff_geneset_filter1 <- IR_diff_geneset_filter1[!duplicated(IR_diff_geneset_filter1)]
tpm_IR_diff <- tpm_matrix[IR_diff_geneset_filter1,]



set.seed(1000)
tpm_IR_diff_mean <- data.frame(IR_0h=apply(tpm_IR_diff[,1:2],1,mean),
                                 IR_4h=apply(tpm_IR_diff[,3:4],1,mean),
                                 IR_12h=apply(tpm_IR_diff[,5:6],1,mean))
########### row_km=6
dir.create("05_diff_IR/km_4")

heatmap_IR_diff <- Heatmap(matrix = t(scale(t(tpm_IR_diff_mean))),name="z-score",
                                show_column_names = TRUE,show_row_names=FALSE,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                row_km = 4,
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("05_diff_IR/km_4/heatmap_km4.pdf"))
heatmap_IR_diff <- draw(heatmap_IR_diff)
dev.off()


tpm_newOrder1 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`1`,]
tpm_newOrder2 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`2`,]
tpm_newOrder3 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`3`,]
tpm_newOrder4 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`4`,]
#tpm_newOrder5 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`5`,]
#tpm_newOrder6 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff)$`6`,]
#tpm_newOrder7 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff2)$`7`,]
#tpm_newOrder8 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff2)$`8`,]
#tpm_newOrder9 <- tpm_IR_diff_mean[row_order(heatmap_IR_diff2)$`9`,]

gene_anno <- HeatmapAnnotation(cluster = c(rep("2",dim(tpm_newOrder2)[1]),
                                           rep("1",dim(tpm_newOrder1)[1]),
                                           rep("4",dim(tpm_newOrder4)[1]),
                                           rep("3",dim(tpm_newOrder3)[1])),which = 'row')
colnames(tpm_IR_diff_mean)
heatmap_IR_diff_order <- Heatmap(matrix = t(scale(t(tpm_IR_diff_mean[c(rownames(tpm_newOrder2),
                                            rownames(tpm_newOrder1),
                                            rownames(tpm_newOrder4),
                                            rownames(tpm_newOrder3)),]))),
        name="z-score",
                                show_column_names = TRUE,show_row_names=FALSE,
                                cluster_rows = F,cluster_columns = F,
        left_annotation = gene_anno,
                                width = unit(3,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf("05_diff_IR/km_4/heatmap_km4_order.pdf")
heatmap_IR_diff_order <- draw(heatmap_IR_diff_order)
dev.off()


write.table(tpm_newOrder1,"05_diff_IR/km_4/tpm_newOrder1.txt",quote = F)
write.table(tpm_newOrder2,"05_diff_IR/km_4/tpm_newOrder2.txt",quote = F)
write.table(tpm_newOrder3,"05_diff_IR/km_4/tpm_newOrder3.txt",quote = F)
write.table(tpm_newOrder4,"05_diff_IR/km_4/tpm_newOrder4.txt",quote = F)

write.table(rownames(tpm_newOrder1),"05_diff_IR/km_4/newOrder1_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder2),"05_diff_IR/km_4/newOrder2_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder3),"05_diff_IR/km_4/newOrder3_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder4),"05_diff_IR/km_4/newOrder4_genes.txt",quote = F,row.names = F,col.names = F)



dir.create("05_diff_IR/km_4/01_GO")
keytypes(org.Mm.eg.db)


for (i in 1:4){
   assign(paste0("Go_",i),transGO(i,"05_diff_IR/km_4/01_GO/"))
}

for (i in 1:4){
        assign(paste0("KEGG_",i),transKEGG(i))
}

```
```{r gsea}


```

```{r diff_M3IN cluster}
dir.create("05_diff_M3IN")
M3IN_diff_geneset_filter1 <- c(rownames(res_M3IN_0h_4h_filter_1),
                       rownames(res_M3IN_4h_12h_filter_1),
                       rownames(res_M3IN_0h_12h_filter_1))

M3IN_diff_geneset_filter1 <- M3IN_diff_geneset_filter1[!duplicated(M3IN_diff_geneset_filter1)]

tpm_M3IN_diff <- tpm_matrix[M3IN_diff_geneset_filter1,]


set.seed(1000)
tpm_M3IN_diff_mean <- data.frame(M3IN_0h=apply(tpm_M3IN_diff[,1:2],1,mean),
                                 M3IN_4h=apply(tpm_M3IN_diff[,3:4],1,mean),
                                 M3IN_12h=apply(tpm_M3IN_diff[,5:6],1,mean))
########### row_km=6
dir.create("05_diff_M3IN/km_4")

heatmap_M3IN_diff <- Heatmap(matrix = t(scale(t(tpm_M3IN_diff_mean))),name="z-score",
                                show_column_names = TRUE,show_row_names=FALSE,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                row_km = 6,
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("05_diff_M3IN/km_4/heatmap_km6.pdf"))
heatmap_M3IN_diff <- draw(heatmap_M3IN_diff)
dev.off()


tpm_newOrder1 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`1`,]
tpm_newOrder2 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`2`,]
tpm_newOrder3 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`3`,]
tpm_newOrder4 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`4`,]
tpm_newOrder5 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`5`,]
tpm_newOrder6 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff)$`6`,]
#tpm_newOrder7 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff2)$`7`,]
#tpm_newOrder8 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff2)$`8`,]
#tpm_newOrder9 <- tpm_M3IN_diff_mean[row_order(heatmap_M3IN_diff2)$`9`,]

gene_anno <- HeatmapAnnotation(cluster = c(rep("2",dim(tpm_newOrder2)[1]),
                                           rep("1",dim(tpm_newOrder1)[1]),
                                           rep("3",dim(tpm_newOrder3)[1]),
                                           rep("6",dim(tpm_newOrder6)[1]),
                                           rep("5",dim(tpm_newOrder5)[1]),
                                           rep("4",dim(tpm_newOrder4)[1])),which = 'row')
colnames(tpm_M3IN_diff_mean)
heatmap_M3IN_diff_order <- Heatmap(matrix = t(scale(t(tpm_M3IN_diff_mean[c(rownames(tpm_newOrder2),
                                            rownames(tpm_newOrder1),
                                            rownames(tpm_newOrder3),
                                            rownames(tpm_newOrder6),
                                            rownames(tpm_newOrder5),
                                            rownames(tpm_newOrder4)),]))),
        name="z-score",
                                show_column_names = TRUE,show_row_names=FALSE,
                                cluster_rows = F,cluster_columns = F,
        left_annotation = gene_anno,
                                width = unit(3,'inches'),
                                col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf("05_diff_M3IN/km_4/heatmap_km6_order.pdf")
heatmap_M3IN_diff_order <- draw(heatmap_M3IN_diff_order)
dev.off()


write.table(tpm_newOrder1,"05_diff_M3IN/km_4/tpm_newOrder1.txt",quote = F)
write.table(tpm_newOrder2,"05_diff_M3IN/km_4/tpm_newOrder2.txt",quote = F)
write.table(tpm_newOrder3,"05_diff_M3IN/km_4/tpm_newOrder3.txt",quote = F)
write.table(tpm_newOrder4,"05_diff_M3IN/km_4/tpm_newOrder4.txt",quote = F)
write.table(tpm_newOrder5,"05_diff_M3IN/km_4/tpm_newOrder5.txt",quote = F)
write.table(tpm_newOrder6,"05_diff_M3IN/km_4/tpm_newOrder6.txt",quote = F)

write.table(rownames(tpm_newOrder1),"05_diff_M3IN/km_4/newOrder1_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder2),"05_diff_M3IN/km_4/newOrder2_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder3),"05_diff_M3IN/km_4/newOrder3_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder4),"05_diff_M3IN/km_4/newOrder4_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder5),"05_diff_M3IN/km_4/newOrder5_genes.txt",quote = F,row.names = F,col.names = F)
write.table(rownames(tpm_newOrder6),"05_diff_M3IN/km_4/newOrder6_genes.txt",quote = F,row.names = F,col.names = F)

options(stringsAsFactors = FALSE)
library(ggrepel)
library(stringr)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(ggplot2)
library(clusterProfiler)
library(org.Mm.eg.db)
keytypes(org.Mm.eg.db)

library(data.table)

# 1. id transform
# biomart
library(biomaRt)
library(data.table)
# bitr in clusterProfiler

dir.create("05_diff_M3IN/km_4/01_GO")



for (i in 1:6){
   assign(paste0("Go_",i),transGO(i))
}




for (i in 1:6){
        assign(paste0("KEGG_",i),transKEGG(i))
}
```

```{r}
library(ComplexHeatmap)
Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% read.table("~/Data/01_TC1/00_gene_set/Toti_genes")$V1,]))),name="z-score",
        show_column_names = TRUE,show_row_names=T,
        cluster_rows = T,cluster_columns = F,
        width = unit(4,'inches'),
        col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                 colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))

Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% read.table("~/Data/01_TC1/00_gene_set/Pluri_genes")$V1,]))),name="z-score",
        show_column_names = TRUE,show_row_names=T,
        cluster_rows = T,cluster_columns = F,
        width = unit(4,'inches'),
        col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                 colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))

Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% read.table("~/Data/01_TC1/00_gene_set/PrE_genes")$V1,]))),name="z-score",
        show_column_names = TRUE,show_row_names=T,
        cluster_rows = T,cluster_columns = F,
        width = unit(4,'inches'),
        col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                 colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))

Heatmap(matrix = t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% read.table("~/Data/01_TC1/00_gene_set/Trophectoderm_markers")$V1,]))),name="z-score",
        show_column_names = TRUE,show_row_names=T,
        cluster_rows = T,cluster_columns = F,
        width = unit(4,'inches'),
        col=circlize::colorRamp2(c(-1.5,0,1.5), 
                                 colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
