---
title: "r01_DEG_mRNA_p6_siNudt21"
author: "Tang Li"
date: '2023-2-11'
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(DESeq2)
library(GEOquery)
library(GenomicFeatures)
library(BiocParallel)
library(GenomicAlignments)
library(rtracklayer)
library(NMF)
library(parallel)
library(Rsubread)
library(RUVSeq)
library(stringr)
library(data.table)
library(ggplot2)
library(ggprism)
library(RColorBrewer)
library(ttFunctions)
library(ggthemes)
library(ggsci)
library(ggpubr)
library(ComplexHeatmap)
library(sva)
library(venn)
options(stringsAsFactors = FALSE)
library(ggrepel)
library(clusterProfiler)
library(org.Mm.eg.db)
library(biomaRt)
library(enrichplot)
library(patchwork)
library(VennDiagram)



# ~/Data/01_TC1/01_mRNA_expression/03_p6_siNudt21/03_p6_siNudt21.Rproj

require("knitr")
opts_knit$set(root.dir = file.path("~/Data/01_TC1/01_mRNA_expression/03_p6_siNudt21/"))

```

```{r filt genes with duplicated gene name}
fc_result_count <- read.table("../01_p0p5p10rp2/01_featureCounts/express_matrix_count.txt")
fc_result_annotation <- read.table("../01_p0p5p10rp2/01_featureCounts/express_matrix_annotation.txt")

table(duplicated(fc_result_annotation$gene_name))

fc_result_count <- fc_result_count[!duplicated(fc_result_annotation$gene_name),]
fc_result_annotation <- fc_result_annotation[rownames(fc_result_count),]

rownames(fc_result_count) <- fc_result_annotation$gene_name
rownames(fc_result_annotation) <- fc_result_annotation$gene_name


```

```{r marker genes}
marker_all <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//all")$V1
marker_toti <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//toti")$V1
marker_pluri <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//pluri")$V1
marker_TE_TSC <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//TE_TSC")$V1
marker_TSC <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//TSC")$V1
marker_PrE_XEN <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//PrE_XEN")$V1
marker_APA <- read.table("~/Data/01_TC1/00_gene_set/all_20230213_p0p10rp2//APA")$V1
marker_APAperturb <- read.table("~/Data/01_TC1/00_gene_set/all/APA_perturb")$V1

table(marker_all %in% rownames(express_matrix))
marker_all[!marker_all %in% rownames(express_matrix)]
marker_all <- marker_all[marker_all %in% rownames(express_matrix)]
```
### DEG for p6_siNudt21

```{r betweenLaneNormalization & expression filter10}

sample_name <- paste(rep(c("siNC","siNudt21_1","siNudt21_3"),each=2),rep(c("rep1","rep2"),times=3),sep = "_")
express_matrix <- fc_result_count[,1:6]
colnames(express_matrix) <- sample_name
meta_data <- data.frame(rep = rep(c("rep1","rep2"),times=3),
                        stage = rep(c("siNC","siNudt21_1","siNudt21_3"),each=2),
                        row.names = sample_name,
                        sample_name = sample_name,
                        stringsAsFactors = TRUE)
meta_data

x <- meta_data$stage
set <- newSeqExpressionSet(as.matrix(express_matrix),
                           phenoData = data.frame(x, row.names=colnames(express_matrix)))
set

colors <- brewer.pal(18, "Paired")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

set <- betweenLaneNormalization(set, which="upper")
plotRLE(set, outline=FALSE, ylim=c(-2, 2), col=colors[x])
plotPCA(set, col=colors[x], cex=1.2)

express_matrix <- set@assayData$normalizedCounts

dir.create("02_express_matrix")
tt_wt(express_matrix,"02_express_matrix/express_matrix.txt",row.names=T,col.names = T)
# 对表达量进行筛选
filter <- rowSums(express_matrix>10)>=2
table(filter)
express_matrix_filter10 <- express_matrix[filter,]

colnames(express_matrix_filter10)
tt_wt(express_matrix_filter10,"02_express_matrix/express_matrix_filter10.txt",row.names=T,col.names = T)
```

```{r get tpm_matrix}
#convert to TPM

tpm_matrix <- do.call(cbind,base::lapply(colnames(express_matrix),FUN = function(x){
  counts <- express_matrix[,x]
  effLen <- fc_result_annotation[rownames(express_matrix),"Length"]
  rate <- log(counts) - log(effLen)
  denom <- log(sum(exp(rate)))
  return(exp(rate-denom+log(1e6)))
}))

rownames(tpm_matrix) <- rownames(express_matrix)
colnames(tpm_matrix) <- colnames(express_matrix)
table(colSums(tpm_matrix))

write.table(tpm_matrix,file="02_express_matrix/tpm_matrix.txt",quote = F,sep = "\t")
```

## DESeq2
### PCA
```{r create dir}
dir.create("03_PCA")
```

```{r PCA - all gene}

meta_data 
colnames(express_matrix)

dds <- DESeqDataSetFromMatrix(countData = express_matrix,colData = meta_data,design = ~ stage)

#pca plot

rlog <- rlog(dds,blind = FALSE)

pcaData <- plotPCA(rlog,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA rlog")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/01_allgene_rlog.pdf",width = 8,height = 7)
print(p1)
dev.off()

vst <- vst(dds,blind = FALSE)

pcaData <- plotPCA(vst,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA vst")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/01_allgene_vst.pdf",width = 8,height = 7)
print(p1)
dev.off()
```

```{r PCA - marker gene}

meta_data 
colnames(express_matrix)

dds <- DESeqDataSetFromMatrix(countData = express_matrix[marker_all,],colData = meta_data,design = ~ stage)

#pca plot

rlog <- rlog(dds,blind = FALSE)

pcaData <- plotPCA(rlog,intgroup = c("stage"),returnData = TRUE,ntop=500)
pcaData
percentVar <- round(100 * attr(pcaData,"percentVar"))
percentVar

p1 <- ggplot(pcaData,aes(x = PC1, y = PC2, color=stage)) +
  geom_point(size=3) +
  #geom_label(aes(label=stage,vjust=1))+
  xlab(paste0("PC1:",percentVar[1],"% variance")) +
  ylab(paste0("PC2:",percentVar[2],"% variance")) +
  #xlim(-15,15)+
  #ylim(-15,10)+
  coord_fixed(ratio=percentVar[2]/percentVar[1]) +
  ggtitle("PCA plot mRNA rlog")+
  theme_bw()
  #scale_color_prism(palette = "floral")
  #scale_color_manual(values = c("M3IN_0h" = "#facf87", "M3IN_4h" = "#d1d1ed", "M3IN_12h" = "#b9dbf4"))


pdf("03_PCA/02_allmarker_rlog.pdf",width = 8,height = 7)
print(p1)
dev.off()
```

### for DEG analysis
```{r create dds object}

dds <- DESeqDataSetFromMatrix(countData = express_matrix_filter10,colData = meta_data,design = ~ stage)

dir.create("04_DEG_result")
dir.create("05_DEG_heatmap")
dir.create("06_DEG_volcano")
```

```{r DEG analysis}

#DEG
dds <- DESeq(dds)
resultsNames(dds)

res_siNC_siNudt21_1 <- tt_DEG_result(dds,"siNC","siNudt21_1","04_DEG_result")
res_siNC_siNudt21_3 <- tt_DEG_result(dds,"siNC","siNudt21_3","04_DEG_result")

```

## filter1
```{r DEG result filter1}
#filter1

res_siNC_siNudt21_1_filter_1 <- tt_DEG_filter(res_siNC_siNudt21_1,"siNC","siNudt21_1","04_DEG_result",lfcThreshold = 1)
res_siNC_siNudt21_3_filter_1 <- tt_DEG_filter(res_siNC_siNudt21_3,"siNC","siNudt21_3","04_DEG_result",lfcThreshold = 1)

```

```{r DEG heatmap filter1}

tt_DEG_heatmap(res_siNC_siNudt21_1_filter_1,"siNC","siNudt21_1",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)
tt_DEG_heatmap(res_siNC_siNudt21_3_filter_1,"siNC","siNudt21_3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1)

### cluster col
tt_DEG_heatmap(res_siNC_siNudt21_1_filter_1,"siNC","siNudt21_1",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1,cluster_columns = T,name_suffix = "_cluster_col")
tt_DEG_heatmap(res_siNC_siNudt21_3_filter_1,"siNC","siNudt21_3",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 1,cluster_columns = T,name_suffix = "_cluster_col")

```

```{r DEG volcano filter1}
tt_DEG_volcano(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")
tt_DEG_volcano(res_siNC_siNudt21_3,"siNC","siNudt21_3","06_DEG_volcano/",lfcThreshold =1,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

tt_DEG_volcano_mark(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siNudt21_3,"siNC","siNudt21_3","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =1,label_genes=marker_toti,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_toti")
```

```{r DEG GO KEGG filter1}

dir.create("07_DEG_GO")

sn <- c("siNC","siNudt21_1","siNudt21_3")
for (i in sn[1]){
  for (j in sn[2:3]){
    if (exists(paste0("res_",i,"_",j,"_filter_1"))){
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_1")))[get(paste0("res_",i,"_",j,"_filter_1"))$log2FoldChange>0],groupname = paste0("res_",i,"_",j,"_filter_1_up"),filedir = "07_DEG_GO/")
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_1")))[get(paste0("res_",i,"_",j,"_filter_1"))$log2FoldChange<0],groupname = paste0("res_",i,"_",j,"_filter_1_down"),filedir = "07_DEG_GO/")
    }
  }
}

```

## filter058
```{r DEG result filter058}

res_siNC_siNudt21_1_filter_058 <- tt_DEG_filter(res_siNC_siNudt21_1,"siNC","siNudt21_1","04_DEG_result",lfcThreshold = 0.58)

```

```{r DEG heatmap filter058}

tt_DEG_heatmap(res_siNC_siNudt21_1_filter_058,"siNC","siNudt21_1",tpm_matrix[,1:4],meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 0.58,pdf_width = 4)

group <- c("toti","pluri","PrE_XEN","TE_TSC","TSC","APAperturb")
for (i in group){
  print(i)
  print(get(paste0("marker_",i))[get(paste0("marker_",i)) %in% rownames(res_siNC_siNudt21_1_filter_058[res_siNC_siNudt21_1_filter_058$log2FoldChange<0,])])
}

for (i in group){
  print(i)
  print(get(paste0("marker_",i))[get(paste0("marker_",i)) %in% rownames(res_siNC_siNudt21_1_filter_058[res_siNC_siNudt21_1_filter_058$log2FoldChange>0,])])
}


### cluster col
tt_DEG_heatmap(res_siNC_siNudt21_1_filter_058,"siNC","siNudt21_1",tpm_matrix,meta_data,save_dir = "05_DEG_heatmap/",lfcThreshold = 0.58,cluster_columns = T,name_suffix = "_cluster_col")

```

```{r DEG volcano filter058}
tt_DEG_volcano(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =0.58,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_padj100")

tt_DEG_volcano_mark(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =0.58,label_genes=marker_APA,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_APA")

tt_DEG_volcano_mark(res_siNC_siNudt21_1,"siNC","siNudt21_1","06_DEG_volcano/",lfcThreshold =0.58,label_genes=marker_toti,pdf_width = 8,pdf_height = 6,padj_limit = 100,name_suffix = "_mark_toti")
```

```{r DEG GO KEGG filter058}

for (i in sn[1]){
  for (j in sn[2]){
    if (exists(paste0("res_",i,"_",j,"_filter_058"))){
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_058")))[get(paste0("res_",i,"_",j,"_filter_058"))$log2FoldChange>0],groupname = paste0("res_",i,"_",j,"_filter_058_up"),filedir = "07_DEG_GO/")
      tt_enrichGO(genelist = rownames(get(paste0("res_",i,"_",j,"_filter_058")))[get(paste0("res_",i,"_",j,"_filter_058"))$log2FoldChange<0],groupname = paste0("res_",i,"_",j,"_filter_058_down"),filedir = "07_DEG_GO/")
    }
  }
}

```

## marker 
```{r marker barplot}

tt_barplot <- function(gene_name){
  temp <- data.frame(group=factor(c("siNC","siNC","siNudt21","siNudt21"),levels = c("siNC","siNudt21")),
                   tpm=tpm_matrix[gene_name,1:4])
  p1 <- ggplot(temp, aes(x = group, y = tpm, fill=group)) +
  geom_bar(stat = "summary",fun=mean,position="dodge",width =0.8,show.legend = F,size=2)+ #绘制柱状图
  geom_point(show.legend = F,position = position_jitter(width = 0.1))+
  stat_summary(geom = "errorbar",fun.data = 'mean_sdl', width = 0.3,show.legend = F)+#误差棒
  labs(x=NULL,y=paste0(gene_name," tpm"))+#标题
  theme_prism(palette = "floral",
              base_fontface = "plain", # 字体样式，可选 bold, plain, italic
              base_family = "sans", # 字体格式，可选 serif, sans, mono, Arial等
              base_size = 16,  # 图形的字体大小
              base_line_size = 0.8, # 坐标轴的粗细
              axis_text_angle = 0)+ # 可选值有 0，45，90，270
   scale_fill_manual(values = c("siNC" = "#DB5C25", "siNudt21" = "#F3B747", "mESC" = "#649541"))+
  theme(plot.title = element_text(size=16,hjust = -0.5))
  #scale_color_manual(values = c("0h" = "#c6a46b", "4h" = "#a4a4ba", "12h" = "#92adc1"))
  #scale_color_manual(values = c("0h" = "#ecc37f", "4h" = "#c5c5e0", "12h" = "#aecfe7"))
  #scale_fill_prism(palette = "floral")#使用ggprism包修改颜色
  print(p1)
}

dir.create("08_marker")
pdf("08_marker/01_APA_barplot.pdf",width = 3.5,height = 4)
for (i in marker_APA[marker_APA %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
tt_barplot("Gapdh")
tt_barplot("Actb")
dev.off()

pdf("08_marker/02_toti_barplot.pdf",width = 3.5,height = 4)
for (i in marker_toti[marker_toti %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/03_pluri_barplot.pdf",width = 3.5,height = 4)
for (i in marker_pluri[marker_pluri %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/04_TE_TSC_barplot.pdf",width = 3.5,height = 4)
for (i in marker_TE_TSC[marker_TE_TSC %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/05_PrE_XEN_barplot.pdf",width = 3.5,height = 4)
for (i in marker_PrE_XEN[marker_PrE_XEN %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
dev.off()

pdf("08_marker/06_APAperturb_barplot.pdf",width = 3.5,height = 4)
for (i in marker_APAperturb[marker_APAperturb %in% rownames(tpm_matrix)]){
  tt_barplot(i)
}
tt_barplot("Gapdh")
tt_barplot("Actb")
dev.off()
```

```{r marker heatmap}
group <- c("toti","pluri","PrE_XEN","TE_TSC","TSC","APAperturb")

for (i in group){
  temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% get(paste0("marker_",i)),c(1,2,3:4)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/08_heatmap_cluster_col_",i,".pdf"))
heatmap <- draw(heatmap)
dev.off()

}

temp <- c("Eif1ad7","Snai1","Gpx3","Ddit4l","Mmp19","Zscan4c","Tbx15","Nrp1","Emp3","Bmpr2","Ctsb","Prnp","Egfr","Plk2","Duxbl1","Btg2","Ddr2","Mdm2","Cd81","Cdkn1a","Glrx2","Dysf","Trp53inp1","Zscan4d","Kit","Pou2f3","Lin28a","Tcf15","Mapk12","H2az1","Tfrc","Sox2","Nop10","H2ax","Ddit3","Utf1","Upp1","A2m","Rest","Lin28b","Pim2")
  temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% temp,c(1,2,3:4)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/08_heatmap_cluster_col_select.pdf"))
heatmap <- draw(heatmap)
dev.off()
```

## gsea
```{r gsea ribo mito}
# 创建文件夹
dir.create("08_marker_gsea")

# 读取基因集
Ribosome_genes <- read.table("../../00_gene_set/CC_Ribosome")$V1
ribosome_biogenesis_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/ribosome_biogenesis")$V1
mitochondrial_protein_containing_complex_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrial_protein_containing_complex")$V1
mitochondrion_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/mitochondrion_organization")$V1
extracellular_matrix_organization_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix_organization")$V1
extracellular_matrix_genes <- read.table("~/Data/01_TC1/user_08_TC1/00_gene_set/extracellular_matrix")$V1

# 将基因集按照对应的GO term分类
term_ <- c(rep("GO_ribosome_biogenesis",length(ribosome_biogenesis_genes)),
                            rep("GO_Ribosome",length(Ribosome_genes)),
                            rep("GO_mitochondrial_protein_complex",length(mitochondrial_protein_containing_complex_genes)),
                            rep("GO_mitochondrion_organization",length(mitochondrion_organization_genes)),
                            rep("GO_extracellular_matrix_organization",length(extracellular_matrix_organization_genes)),
                            rep("GO_extracellular_matrix",length(extracellular_matrix_genes)))
gene_ <- c(ribosome_biogenesis_genes,Ribosome_genes,
                            mitochondrial_protein_containing_complex_genes,mitochondrion_organization_genes,
                            extracellular_matrix_organization_genes,extracellular_matrix_genes)
msigdb <- data.frame(term=term_,
                     gene=gene_)

# 获取差异基因列表
res_siNC_siNudt21_1_list <- res_siNC_siNudt21_1$log2FoldChange
names(res_siNC_siNudt21_1_list) <- rownames(res_siNC_siNudt21_1)
res_siNC_siNudt21_1_list <- sort(res_siNC_siNudt21_1_list,decreasing = T)

# 进行GSEA分析
gsea <- GSEA(res_siNC_siNudt21_1_list,TERM2GENE = msigdb,
             pvalueCutoff = 1,maxGSSize = 2000,minGSSize = 5,
             eps=1e-100,
             nPermSimple = 10000)

# 绘制GSEA图
terms <- c("GO_ribosome_biogenesis",
           "GO_Ribosome",
           "GO_mitochondrial_protein_complex",
           "GO_mitochondrion_organization",
           "GO_extracellular_matrix_organization",
           "GO_extracellular_matrix")

# 绘制GSEA图并保存
library(GseaVis)
gseaList1 <- lapply(terms, function(x){
  gseaNb(object = gsea,
         geneSetID = x,
         addPval = T,
         subPlot = 2)
})

lapply(terms[c(1,3)], function(x){
  gseaNb(object = gsea,
         geneSetID = x,
         addPval = T,
         pvalX = 0.55,pvalY = 0.25,
         subPlot = 2)
}) -> gseaList2

pdf("08_marker_gsea/gsea_siNudt21_1.pdf",width = 4,height = 4)
print(gseaList1)
print(gseaList2)
dev.off()

gseaList <- list(gseaList1[[1]],gseaList2[[1]],gseaList2[[2]])

pdf("08_marker_gsea/gsea_siNudt21_1_combine.pdf",width = 12,height = 4.5)
cowplot::plot_grid(plotlist = gseaList,ncol = 3,align = 'hv')
dev.off()

```

```{r gsea gseGO}
# 将res_siNC_siNudt21_1_list_转换为数据框
res_siNC_siNudt21_1_list_ <- as.data.frame(res_siNC_siNudt21_1[,c(2,5)])
# 添加SYMBOL列
res_siNC_siNudt21_1_list_$SYMBOL <- rownames(res_siNC_siNudt21_1_list_)

# 将SYMBOL转换为ENTREZID
df <- bitr(rownames(res_siNC_siNudt21_1_list_),
           fromType = "SYMBOL",
           toType = "ENTREZID",
           OrgDb = org.Mm.eg.db)

# 将ENTREZID添加到res_siNC_siNudt21_1_list_中
res_siNC_siNudt21_1_list_ <- merge(res_siNC_siNudt21_1_list_,df,by="SYMBOL")

# 获取基因列表
genelist <- res_siNC_siNudt21_1_list_$log2FoldChange
names(genelist) <- res_siNC_siNudt21_1_list_$ENTREZID
genelist <- sort(genelist,decreasing = T)

# 进行GO分析
GO_kk_entrez <- gseGO(geneList = genelist,
                      ont = "All",
                      OrgDb = org.Mm.eg.db,
                      keyType = "ENTREZID",
                      eps = 1e-100,
                      pvalueCutoff = 0.1)

# 保存结果
save(GO_kk_entrez, file = "08_marker_gsea/GSEA_result_siNudt21_1.RData")

# 将ENTREZID转换为可读性更好的形式
GO_kk <- DOSE::setReadable(GO_kk_entrez,
                           OrgDb = org.Mm.eg.db,
                           keyType = "ENTREZID")

# 选择p值小于0.01且NES绝对值大于1的结果
GO_kk_cut <- GO_kk[GO_kk@result$p.adjust<0.01 & abs(GO_kk@result$NES)>1,]

# 分别选择NES大于0和小于0的结果
GO_kk_cut_up <- subset(GO_kk_cut,NES>0)
GO_kk_cut_down <- subset(GO_kk_cut,NES<0)

# 进行GSEA分析
gseaNb(object = GO_kk_entrez,
         geneSetID = "GO:0044391",
         addPval = T,
         subPlot = 2)

# 生成GSEA GO富集分析结果的散点图
# 绘制GO_kk_cut_down的散点图
pdf("08_marker_gsea/gsea_GO_cut_down_q0.01.pdf",width = 6,height = 5)

# 按照pvalue从大到小排序
GO_kk_cut_down <- GO_kk_cut_down[order(GO_kk_cut_down$pvalue,decreasing = T),]
# 将Description转换为factor类型，并按照原始顺序排序
GO_kk_cut_down$Description <- factor(GO_kk_cut_down$Description, levels = GO_kk_cut_down$Description)
# 绘制散点图
ggplot(tail(GO_kk_cut_down,10), aes(x=-log10(pvalue), y=Description, size=abs(NES), color=abs(NES))) +
  geom_point() +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_classic() +
  labs(x="-log10(pValue)", y=NULL)+
  theme(axis.text = element_text(size=10))
dev.off()

# 绘制GO_kk_cut_up的散点图
pdf("08_marker_gsea/gsea_GO_cut_up_q0.01.pdf",width = 5,height = 6)
# 按照pvalue从大到小排序
GO_kk_cut_up <- GO_kk_cut_up[order(GO_kk_cut_up$pvalue,decreasing = T),]
# 将Description转换为factor类型，并按照原始顺序排序
GO_kk_cut_up$Description <- factor(GO_kk_cut_up$Description, levels = GO_kk_cut_up$Description)
# 绘制散点图
ggplot(tail(GO_kk_cut_up,10), aes(x=-log10(pvalue), y=Description, size=abs(NES), color=abs(NES))) +
  geom_point() +
  scale_color_gradient(low = "yellow", high = "red") +
  theme_classic() +
  labs(x="-log10_pValue", y=NULL)+
  theme(axis.text = element_text(size=10))
dev.off()
```

## 与p0p10进行比较
```{r log2FC_histgram}
hist(res_siNC_siNudt21_1$log2FoldChange,breaks = 100)

res_p0_p10 <- read.table("../01_p0p5p10rp2/04_DEG_result/res_p0_p10.txt")

hist(res_p0_p10$log2FoldChange,breaks = 100)

```

```{r log2FC correlation}

pdf("04_DEG_result/correlation.pdf",width = 4,height = 4)

res_p0_p10_ <- transform(res_p0_p10,gene=rownames(res_p0_p10))
res_siNC_siNudt21_1_ <- transform(as.data.frame(res_siNC_siNudt21_1),gene=rownames(res_siNC_siNudt21_1))

log2FC_p0p10_siNudt21 <- merge(res_p0_p10_,res_siNC_siNudt21_1_,by="gene")

log2FC_p0p10_siNudt21 <- subset(log2FC_p0p10_siNudt21,select=c("gene","log2FoldChange.x","log2FoldChange.y"))
names(log2FC_p0p10_siNudt21)[2:3] <- c("log2FC_p0p10","log2FC_siNudt21_1")

ggplot(log2FC_p0p10_siNudt21,aes(x=log2FC_p0p10,y=log2FC_siNudt21_1))+
  geom_point(aes(x=log2FC_p0p10,y=log2FC_siNudt21_1))+
  theme_pubr()+
  stat_cor(method = "pearson")


res_siM3_1 <- read.table("../05_p16_siVirma/04_DEG_result/res_siNC_siM3_1.txt")
res_siM3_1_ <- transform(res_siM3_1,gene=rownames(res_siM3_1))

log2FC_siM3_1_siNudt21 <- merge(res_siM3_1_,res_siNC_siNudt21_1_,by="gene")

log2FC_siM3_1_siNudt21 <- subset(log2FC_siM3_1_siNudt21,select=c("gene","log2FoldChange.x","log2FoldChange.y"))
names(log2FC_siM3_1_siNudt21)[2:3] <- c("log2FC_siM3_1","log2FC_siNudt21_1")

ggplot(log2FC_siM3_1_siNudt21,aes(x=log2FC_siM3_1,y=log2FC_siNudt21_1))+
  geom_point(aes(x=log2FC_siM3_1,y=log2FC_siNudt21_1))+
  theme_pubr()+
  stat_cor(method = "pearson")

log2FC_siM3_1_siNudt21_ribo <- log2FC_siM3_1_siNudt21[log2FC_siM3_1_siNudt21$gene %in% Ribosome_genes,]
ggplot(log2FC_siM3_1_siNudt21_ribo,aes(x=log2FC_siM3_1,y=log2FC_siNudt21_1))+
  geom_point(aes(x=log2FC_siM3_1,y=log2FC_siNudt21_1))+
  theme_pubr()+
  stat_cor(method = "pearson")

res_siM3_2 <- read.table("../05_p16_siVirma/04_DEG_result/res_siNC_siM3_2.txt")
res_siM3_2_ <- transform(res_siM3_2,gene=rownames(res_siM3_2))

log2FC_siM3_2_siNudt21 <- merge(res_siM3_2_,res_siNC_siNudt21_1_,by="gene")

log2FC_siM3_2_siNudt21 <- subset(log2FC_siM3_2_siNudt21,select=c("gene","log2FoldChange.x","log2FoldChange.y"))
names(log2FC_siM3_2_siNudt21)[2:3] <- c("log2FC_siM3_2","log2FC_siNudt21_1")

ggplot(log2FC_siM3_2_siNudt21,aes(x=log2FC_siM3_2,y=log2FC_siNudt21_1))+
  geom_point(aes(x=log2FC_siM3_2,y=log2FC_siNudt21_1))+
  theme_pubr()+
  stat_cor(method = "pearson")

log2FC_siM3_2_siNudt21_ribo <- log2FC_siM3_2_siNudt21[log2FC_siM3_2_siNudt21$gene %in% Ribosome_genes,]
ggplot(log2FC_siM3_2_siNudt21_ribo,aes(x=log2FC_siM3_2,y=log2FC_siNudt21_1))+
  geom_point(aes(x=log2FC_siM3_2,y=log2FC_siNudt21_1))+
  theme_pubr()+
  stat_cor(method = "pearson")

dev.off()

```

```{r log2FC heatmap}

# 将log2FoldChange转化为矩阵
log2FC_siM3_1_siNudt21_matrix <- as.matrix(log2FC_siM3_1_siNudt21[,2:3])
# 按照log2FoldChange排序
log2FC_siM3_1_siNudt21_matrix <- log2FC_siM3_1_siNudt21_matrix[order(log2FC_siM3_1_siNudt21_matrix[,1]),]
# 画热图
Heatmap(log2FC_siM3_1_siNudt21_matrix,cluster_rows = F)


```

```{r DEG top500}

# 创建文件夹
dir.create("04_DEG_result/top500")
# 筛选差异表达基因
res_siNC_siNudt21_1_ft <- subset(as.data.frame(res_siNC_siNudt21_1),padj < 0.05 )
# 按照log2FoldChange排序
res_siNC_siNudt21_1_ft <- res_siNC_siNudt21_1_ft[order(res_siNC_siNudt21_1_ft$log2FoldChange,decreasing = T),]
# 取前500个和后500个
res_siNC_siNudt21_1_ft_up500 <- head(res_siNC_siNudt21_1_ft,500)
res_siNC_siNudt21_1_ft_down500 <- tail(res_siNC_siNudt21_1_ft,500)
# 输出差异表达基因列表
tt_wt(res_siNC_siNudt21_1_ft_up500,"04_DEG_result/top500/res_siNC_siNudt21_1_ft_up500.txt",row.names = T,col.names = T)
tt_wt(res_siNC_siNudt21_1_ft_down500,"04_DEG_result/top500/res_siNC_siNudt21_1_ft_down500.txt",row.names = T,col.names = T)
# 输出差异表达基因列表的基因名
tt_wt(rownames(res_siNC_siNudt21_1_ft_up500),"04_DEG_result/top500/res_siNC_siNudt21_1_ft_up500_gene.txt")
tt_wt(rownames(res_siNC_siNudt21_1_ft_down500),"04_DEG_result/top500/res_siNC_siNudt21_1_ft_down500_gene.txt")
# GO富集分析
tt_enrichGO(rownames(res_siNC_siNudt21_1_ft_up500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siNudt21_1_ft_up500")
tt_enrichGO(rownames(res_siNC_siNudt21_1_ft_down500),filedir = "04_DEG_result/top500",groupname = "res_siNC_siNudt21_1_ft_down500")


```

```{r tpm_heatmap APA_perturb Nudt21_LACE_target}
APA_perturb_target <- read.table("../../26_LACE_seq_Nudt21/04_hisat2_mapping/dedup_vs_vs/09_macs2_peak/04_macs2_manual/02_bed_modify/02_annotation/APA_perturb_target")$V1

temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% APA_perturb_target,c(1,2,3:4)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/09_heatmap_APA_perturb_target.pdf"))
heatmap <- draw(heatmap)
dev.off()

temp <- t(scale(t(tpm_matrix[rownames(tpm_matrix) %in% APA_perturb_target,c(1,2,3:4)])))
  temp <- na.omit(temp)
  heatmap <- Heatmap(matrix = temp,name="z-score",
                                show_column_names = TRUE,show_row_names=T,
                                cluster_rows = TRUE,cluster_columns = F,
                                width = unit(4,'inches'),
                                col=circlize::colorRamp2(c(-1.18,0,1.18), 
                                                         colorRampPalette(c("#4875aa", "white", "#d7604c"))(3)))


pdf(paste0("08_marker/09_heatmap_APA_perturb_target.pdf"))
heatmap <- draw(heatmap)
dev.off()

```

